"""
sdk_generator.py — Auto-generate SDKs from OpenAPI Specification
Generates: Python SDK, TypeScript/JS SDK, curl examples
No external dependencies required.
"""

from __future__ import annotations
import json
import re
import textwrap
import urllib.parse
from pathlib import Path
from typing import Any

# Python reserved keywords that cannot be used as parameter names
PYTHON_RESERVED_KEYWORDS = {
    "False", "None", "True", "and", "as", "assert", "async", "await",
    "break", "class", "continue", "def", "del", "elif", "else", "except",
    "finally", "for", "from", "global", "if", "import", "in", "is",
    "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try",
    "while", "with", "yield",
}


# ---------------------------------------------------------------------------
# Type mapping helpers
# ---------------------------------------------------------------------------

PYTHON_TYPE_MAP = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
    "array": "list",
    "object": "dict",
}

TS_TYPE_MAP = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "array": "any[]",
    "object": "Record<string, any>",
}


def to_snake_case(name: str) -> str:
    """Convert camelCase or PascalCase to snake_case."""
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1).lower()


def to_camel_case(name: str) -> str:
    """Convert snake_case to camelCase."""
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def to_pascal_case(name: str) -> str:
    """Convert snake_case or camelCase to PascalCase."""
    s = to_snake_case(name)
    return "".join(p.capitalize() for p in s.split("_"))


def get_python_type(schema: dict, schemas: dict) -> str:
    """Resolve OpenAPI schema to Python type hint."""
    if "$ref" in schema:
        ref_name = schema["$ref"].split("/")[-1]
        return ref_name
    schema_type = schema.get("type", "object")
    if schema_type == "array":
        items = schema.get("items", {})
        inner = get_python_type(items, schemas)
        return f"list[{inner}]"
    return PYTHON_TYPE_MAP.get(schema_type, "Any")


def get_ts_type(schema: dict, schemas: dict) -> str:
    """Resolve OpenAPI schema to TypeScript type."""
    if "$ref" in schema:
        ref_name = schema["$ref"].split("/")[-1]
        return ref_name
    schema_type = schema.get("type", "object")
    if schema_type == "array":
        items = schema.get("items", {})
        inner = get_ts_type(items, schemas)
        return f"{inner}[]"
    return TS_TYPE_MAP.get(schema_type, "any")


# ---------------------------------------------------------------------------
# OpenAPI spec loader
# ---------------------------------------------------------------------------

def load_spec(spec_source: dict | str | Path) -> dict:
    """Load OpenAPI spec from dict, JSON string, or file path."""
    if isinstance(spec_source, dict):
        return spec_source
    if isinstance(spec_source, (str, Path)):
        path = Path(spec_source)
        if path.exists():
            with open(path) as f:
                return json.load(f)
        # Try parsing as JSON string
        return json.loads(spec_source)
    raise ValueError(f"Cannot load spec from: {type(spec_source)}")


# ---------------------------------------------------------------------------
# Python SDK Generator
# ---------------------------------------------------------------------------

class PythonSDKGenerator:
    """Generates a complete Python SDK from OpenAPI 3.1 spec."""

    def __init__(self, spec: dict):
        self.spec = spec
        self.schemas = spec.get("components", {}).get("schemas", {})
        self.paths = spec.get("paths", {})
        self.info = spec.get("info", {})
        self.servers = spec.get("servers", [{}])
        self.base_url = self.servers[0].get("url", "https://api.example.com") if self.servers else ""

    def generate(self) -> str:
        """Generate complete Python SDK as a string."""
        sections = [
            self._generate_header(),
            self._generate_base_client(),
            self._generate_models(),
            self._generate_api_clients(),
            self._generate_main_client(),
            self._generate_footer(),
        ]
        return "\n\n".join(sections)

    def _generate_header(self) -> str:
        title = self.info.get("title", "API")
        version = self.info.get("version", "1.0.0")
        description = self.info.get("description", "")
        return f'''"""
{title} Python SDK — v{version}
{description}

Auto-generated by SintraPrime SDK Generator.
Do not edit manually — regenerate from OpenAPI spec.
"""

from __future__ import annotations
import json
import time
import urllib.request
import urllib.parse
import urllib.error
from typing import Any, Optional, Union
from dataclasses import dataclass, field, asdict
'''

    def _generate_base_client(self) -> str:
        return f'''
# ---------------------------------------------------------------------------
# Base HTTP Client
# ---------------------------------------------------------------------------

class APIError(Exception):
    """Raised when the API returns an error response."""
    def __init__(self, status_code: int, message: str, details: str = ""):
        self.status_code = status_code
        self.message = message
        self.details = details
        super().__init__(f"APIError {{status_code}}: {{message}}")


class BaseClient:
    """Base HTTP client with auth, retry, and rate limiting."""

    DEFAULT_BASE_URL = "{self.base_url}"
    MAX_RETRIES = 3
    RETRY_BACKOFF = 1.5  # seconds

    def __init__(
        self,
        api_key: str = "",
        base_url: str = "",
        timeout: int = 30,
        max_retries: int = 3,
    ):
        self.api_key = api_key
        self.base_url = (base_url or self.DEFAULT_BASE_URL).rstrip("/")
        self.timeout = timeout
        self.max_retries = max_retries

    def _headers(self) -> dict[str, str]:
        headers = {{
            "Content-Type": "application/json",
            "Accept": "application/json",
            "X-SDK-Version": "2.0.0",
            "X-SDK-Language": "python",
        }}
        if self.api_key:
            headers["Authorization"] = f"Bearer {{self.api_key}}"
        return headers

    def _request(
        self,
        method: str,
        path: str,
        params: dict | None = None,
        body: dict | None = None,
    ) -> dict:
        url = self.base_url + path
        if params:
            url += "?" + urllib.parse.urlencode({{k: v for k, v in params.items() if v is not None}})

        data = json.dumps(body).encode() if body else None
        req = urllib.request.Request(url, data=data, headers=self._headers(), method=method)

        last_error = None
        for attempt in range(self.max_retries):
            try:
                with urllib.request.urlopen(req, timeout=self.timeout) as resp:
                    response_body = resp.read().decode()
                    return json.loads(response_body) if response_body else {{}}
            except urllib.error.HTTPError as e:
                error_body = json.loads(e.read().decode()) if e.fp else {{}}
                if e.code == 429:  # Rate limited — always retry
                    wait = self.RETRY_BACKOFF ** attempt
                    time.sleep(wait)
                    last_error = e
                    continue
                raise APIError(e.code, error_body.get("message", str(e)), error_body.get("details", ""))
            except Exception as e:
                if attempt < self.max_retries - 1:
                    time.sleep(self.RETRY_BACKOFF ** attempt)
                    last_error = e
                    continue
                raise

        if last_error:
            raise last_error

    def get(self, path: str, params: dict | None = None) -> dict:
        return self._request("GET", path, params=params)

    def post(self, path: str, body: dict | None = None, params: dict | None = None) -> dict:
        return self._request("POST", path, params=params, body=body)

    def put(self, path: str, body: dict | None = None) -> dict:
        return self._request("PUT", path, body=body)

    def patch(self, path: str, body: dict | None = None) -> dict:
        return self._request("PATCH", path, body=body)

    def delete(self, path: str) -> dict:
        return self._request("DELETE", path)
'''

    def _generate_models(self) -> str:
        lines = ["# ---------------------------------------------------------------------------",
                 "# Data Models (auto-generated from OpenAPI schemas)",
                 "# ---------------------------------------------------------------------------", ""]
        for name, schema in self.schemas.items():
            if schema.get("type") != "object":
                continue
            props = schema.get("properties", {})
            required = schema.get("required", [])
            lines.append("@dataclass")
            lines.append(f"class {name}:")
            desc = schema.get("description", f"{name} model.")
            lines.append(f'    """{desc}"""')
            if not props:
                lines.append("    pass")
            for prop_name, prop_schema in props.items():
                py_type = get_python_type(prop_schema, self.schemas)
                default = "None" if prop_name not in required else "..."
                if default == "None":
                    lines.append(f"    {prop_name}: Optional[{py_type}] = None")
                else:
                    lines.append(f"    {prop_name}: {py_type}")
            lines.append("")
        return "\n".join(lines)

    def _generate_api_clients(self) -> str:
        """Group endpoints by tag and generate API client classes."""
        tag_operations: dict[str, list[dict]] = {}
        for path, path_item in self.paths.items():
            for method, operation in path_item.items():
                if not isinstance(operation, dict):
                    continue
                tags = operation.get("tags", ["Default"])
                for tag in tags:
                    tag_clean = tag.replace("/", "_").replace(" ", "")
                    if tag_clean not in tag_operations:
                        tag_operations[tag_clean] = []
                    tag_operations[tag_clean].append({
                        "path": path,
                        "method": method.upper(),
                        "operation": operation,
                    })

        lines = ["# ---------------------------------------------------------------------------",
                 "# API Client Classes (one per tag)",
                 "# ---------------------------------------------------------------------------", ""]

        for tag, operations in tag_operations.items():
            class_name = f"{to_pascal_case(tag)}API"
            lines.append(f"class {class_name}(BaseClient):")
            lines.append(f'    """API client for {tag} operations."""')
            lines.append("")
            for op_info in operations:
                method_lines = self._generate_python_method(op_info)
                for line in method_lines:
                    lines.append(f"    {line}")
                lines.append("")
            lines.append("")

        return "\n".join(lines)

    def _generate_python_method(self, op_info: dict) -> list[str]:
        """Generate a single Python method for an API operation."""
        path = op_info["path"]
        http_method = op_info["method"]
        operation = op_info["operation"]

        op_id = operation.get("operationId", "")
        method_name = to_snake_case(op_id) if op_id else f"{http_method.lower()}_{path.replace('/', '_').strip('_')}"
        summary = operation.get("summary", "")
        params = operation.get("parameters", [])
        request_body = operation.get("requestBody", {})

        # Build function signature
        args = ["self"]
        path_params = [p for p in params if p.get("in") == "path"]
        query_params = [p for p in params if p.get("in") == "query"]

        for p in path_params:
            p_name = to_snake_case(p["name"])
            if p_name in PYTHON_RESERVED_KEYWORDS:
                p_name = p_name + "_"
            p_type = get_python_type(p.get("schema", {"type": "string"}), self.schemas)
            args.append(f"{p_name}: {p_type}")

        if request_body:
            args.append("body: dict | None = None")

        for p in query_params:
            p_name = to_snake_case(p["name"])
            if p_name in PYTHON_RESERVED_KEYWORDS:
                p_name = p_name + "_"
            p_type = get_python_type(p.get("schema", {"type": "string"}), self.schemas)
            default = p.get("schema", {}).get("default", "None")
            if not p.get("required"):
                args.append(f"{p_name}: Optional[{p_type}] = {repr(default) if default != 'None' else 'None'}")

        sig = f"def {method_name}({', '.join(args)}) -> dict:"
        lines = [sig, f'    """{summary}"""']

        # Build actual path with parameter substitution
        py_path = re.sub(r"\{(\w+)\}", lambda m: "{" + to_snake_case(m.group(1)) + "}", path)
        format_path = f'path = f"{py_path}"'
        lines.append(f"    {format_path}")

        if query_params:
            qp_lines = ["    params = {"]
            for p in query_params:
                p_name = to_snake_case(p["name"])
                if p_name in PYTHON_RESERVED_KEYWORDS:
                    p_name = p_name + "_"
                qp_lines.append(f'        "{p["name"]}": {p_name},')
            qp_lines.append("    }")
            lines.extend(qp_lines)

        if http_method == "GET":
            params_arg = "params=params" if query_params else ""
            lines.append(f"    return self.get(path{', ' + params_arg if params_arg else ''})")
        elif http_method == "POST":
            lines.append("    return self.post(path, body=body)")
        elif http_method == "PUT":
            lines.append("    return self.put(path, body=body)")
        elif http_method == "PATCH":
            lines.append("    return self.patch(path, body=body)")
        elif http_method == "DELETE":
            lines.append("    return self.delete(path)")

        return lines

    def _generate_main_client(self) -> str:
        """Generate the top-level SintraPrime client."""
        title = self.info.get("title", "API").replace(" ", "").replace("-", "")
        tag_names = set()
        for path_item in self.paths.values():
            for operation in path_item.values():
                if isinstance(operation, dict):
                    for tag in operation.get("tags", []):
                        tag_names.add(tag.replace("/", "_").replace(" ", ""))

        init_lines = []
        attrs = []
        for tag in sorted(tag_names):
            class_name = f"{to_pascal_case(tag)}API"
            attr_name = to_snake_case(tag)
            init_lines.append(f"        self.{attr_name} = {class_name}(api_key=api_key, base_url=base_url, timeout=timeout)")
            attrs.append(f"    {attr_name}: {class_name}")

        return f'''
# ---------------------------------------------------------------------------
# Main Client
# ---------------------------------------------------------------------------

class {title.replace(" ", "")}Client:
    """
    Main SintraPrime-Unified API client.

    Usage:
        client = SintraPrimeUnifiedAPIClient(api_key="your-key")
        cases = client.legal_intelligence.search_case_law(query="landlord tenant")
        trust = client.trust_law.create_living_trust(body={{...}})
    """

    def __init__(
        self,
        api_key: str = "",
        base_url: str = "{self.base_url}",
        timeout: int = 30,
    ):
        self.api_key = api_key
        self.base_url = base_url
        self.timeout = timeout
{chr(10).join(init_lines)}

    def __repr__(self) -> str:
        return f"SintraPrimeClient(base_url={{self.base_url!r}})"


# Convenience alias
SintraPrimeClient = {title.replace(" ", "")}Client
'''

    def _generate_footer(self) -> str:
        return '''
# ---------------------------------------------------------------------------
# Module exports
# ---------------------------------------------------------------------------

__all__ = [
    "SintraPrimeClient",
    "APIError",
    "BaseClient",
]
'''

    def save(self, output_path: str | Path) -> Path:
        """Save generated SDK to file."""
        code = self.generate()
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code)
        print(f"✅ Python SDK saved: {path} ({len(code.splitlines())} lines)")
        return path


# ---------------------------------------------------------------------------
# TypeScript SDK Generator
# ---------------------------------------------------------------------------

class TypeScriptSDKGenerator:
    """Generates a TypeScript/JavaScript SDK from OpenAPI 3.1 spec."""

    def __init__(self, spec: dict):
        self.spec = spec
        self.schemas = spec.get("components", {}).get("schemas", {})
        self.paths = spec.get("paths", {})
        self.info = spec.get("info", {})
        self.servers = spec.get("servers", [{}])
        self.base_url = self.servers[0].get("url", "") if self.servers else ""

    def generate(self) -> str:
        sections = [
            self._generate_header(),
            self._generate_types(),
            self._generate_client(),
            self._generate_api_classes(),
            self._generate_exports(),
        ]
        return "\n\n".join(sections)

    def _generate_header(self) -> str:
        title = self.info.get("title", "API")
        version = self.info.get("version", "1.0.0")
        return f'''/**
 * {title} TypeScript SDK — v{version}
 * Auto-generated by SintraPrime SDK Generator.
 * Do not edit manually.
 */

export class APIError extends Error {{
  constructor(
    public statusCode: number,
    public message: string,
    public details?: string
  ) {{
    super(`APIError ${{statusCode}}: ${{message}}`);
    this.name = "APIError";
  }}
}}

export interface RequestOptions {{
  timeout?: number;
  headers?: Record<string, string>;
}}

export interface ClientConfig {{
  apiKey?: string;
  baseUrl?: string;
  timeout?: number;
  maxRetries?: number;
}}'''

    def _generate_types(self) -> str:
        lines = ["// Auto-generated TypeScript interfaces from OpenAPI schemas", ""]
        for name, schema in self.schemas.items():
            if schema.get("type") != "object":
                continue
            props = schema.get("properties", {})
            required = set(schema.get("required", []))
            desc = schema.get("description", "")
            if desc:
                lines.append(f"/** {desc} */")
            lines.append(f"export interface {name} {{")
            for prop_name, prop_schema in props.items():
                ts_type = get_ts_type(prop_schema, self.schemas)
                optional = "" if prop_name in required else "?"
                example = prop_schema.get("example", "")
                comment = f"  // e.g. {example}" if example else ""
                lines.append(f"  {prop_name}{optional}: {ts_type};{comment}")
            lines.append("}")
            lines.append("")
        return "\n".join(lines)

    def _generate_client(self) -> str:
        return f'''// Base HTTP client
export class BaseClient {{
  protected readonly apiKey: string;
  protected readonly baseUrl: string;
  protected readonly timeout: number;
  protected readonly maxRetries: number;

  constructor(config: ClientConfig = {{}}) {{
    this.apiKey = config.apiKey ?? "";
    this.baseUrl = (config.baseUrl ?? "{self.base_url}").replace(/\\/$/, "");
    this.timeout = config.timeout ?? 30000;
    this.maxRetries = config.maxRetries ?? 3;
  }}

  protected async request<T = any>(
    method: string,
    path: string,
    options: {{ params?: Record<string, any>; body?: any }} = {{}}
  ): Promise<T> {{
    let url = this.baseUrl + path;
    if (options.params) {{
      const filteredParams = Object.fromEntries(
        Object.entries(options.params).filter(([_, v]) => v !== undefined && v !== null)
      );
      url += "?" + new URLSearchParams(filteredParams).toString();
    }}

    const headers: Record<string, string> = {{
      "Content-Type": "application/json",
      "Accept": "application/json",
      "X-SDK-Version": "2.0.0",
      "X-SDK-Language": "typescript",
    }};
    if (this.apiKey) {{
      headers["Authorization"] = `Bearer ${{this.apiKey}}`;
    }}

    let lastError: Error | undefined;
    for (let attempt = 0; attempt < this.maxRetries; attempt++) {{
      try {{
        const response = await fetch(url, {{
          method,
          headers,
          body: options.body !== undefined ? JSON.stringify(options.body) : undefined,
          signal: AbortSignal.timeout(this.timeout),
        }});

        if (!response.ok) {{
          const errorBody = await response.json().catch(() => ({{}}));
          if (response.status === 429) {{
            await new Promise(r => setTimeout(r, Math.pow(1.5, attempt) * 1000));
            continue;
          }}
          throw new APIError(response.status, errorBody.message ?? response.statusText, errorBody.details);
        }}

        const text = await response.text();
        return text ? JSON.parse(text) : ({{}}) as T;
      }} catch (err) {{
        lastError = err as Error;
        if (attempt < this.maxRetries - 1) {{
          await new Promise(r => setTimeout(r, Math.pow(1.5, attempt) * 500));
        }}
      }}
    }}
    throw lastError;
  }}

  protected get<T>(path: string, params?: Record<string, any>): Promise<T> {{
    return this.request<T>("GET", path, {{ params }});
  }}

  protected post<T>(path: string, body?: any, params?: Record<string, any>): Promise<T> {{
    return this.request<T>("POST", path, {{ body, params }});
  }}

  protected put<T>(path: string, body?: any): Promise<T> {{
    return this.request<T>("PUT", path, {{ body }});
  }}

  protected patch<T>(path: string, body?: any): Promise<T> {{
    return this.request<T>("PATCH", path, {{ body }});
  }}

  protected delete<T>(path: string): Promise<T> {{
    return this.request<T>("DELETE", path);
  }}
}}'''

    def _generate_api_classes(self) -> str:
        tag_operations: dict[str, list[dict]] = {}
        for path, path_item in self.paths.items():
            for method, operation in path_item.items():
                if not isinstance(operation, dict):
                    continue
                tags = operation.get("tags", ["Default"])
                for tag in tags:
                    tag_clean = tag.replace("/", "_").replace(" ", "")
                    if tag_clean not in tag_operations:
                        tag_operations[tag_clean] = []
                    tag_operations[tag_clean].append({
                        "path": path,
                        "method": method.upper(),
                        "operation": operation,
                    })

        lines = ["// API classes"]
        for tag, operations in tag_operations.items():
            class_name = f"{to_pascal_case(tag)}API"
            lines.append(f"export class {class_name} extends BaseClient {{")
            for op_info in operations:
                path = op_info["path"]
                http_method = op_info["method"]
                operation = op_info["operation"]
                op_id = operation.get("operationId", "")
                method_name = to_camel_case(op_id) if op_id else http_method.lower()
                summary = operation.get("summary", "")
                params = operation.get("parameters", [])
                has_body = bool(operation.get("requestBody"))
                path_params = [p for p in params if p.get("in") == "path"]
                query_params = [p for p in params if p.get("in") == "query"]

                args = []
                for p in path_params:
                    args.append(f"{to_camel_case(p['name'])}: string")
                if has_body:
                    args.append("body?: Record<string, any>")
                for p in query_params:
                    ts_type = get_ts_type(p.get("schema", {"type": "string"}), self.schemas)
                    optional = "" if p.get("required") else "?"
                    args.append(f"{to_camel_case(p['name'])}{optional}: {ts_type}")

                ts_path = re.sub(r"\{(\w+)\}", lambda m: "${" + to_camel_case(m.group(1)) + "}", path)
                lines.append(f"  /** {summary} */")
                lines.append(f"  async {method_name}({', '.join(args)}): Promise<any> {{")
                lines.append(f"    const path = `{ts_path}`;")

                if query_params:
                    qp_names = [to_camel_case(p["name"]) for p in query_params]
                    params_obj = ", ".join(f"{n}: {n}" for n in qp_names)
                    lines.append(f"    const params = {{ {params_obj} }};")

                if http_method == "GET":
                    params_arg = "params" if query_params else "undefined"
                    lines.append(f"    return this.get(path, {params_arg});")
                elif http_method == "POST":
                    lines.append("    return this.post(path, body);")
                elif http_method == "PUT":
                    lines.append("    return this.put(path, body);")
                elif http_method == "PATCH":
                    lines.append("    return this.patch(path, body);")
                elif http_method == "DELETE":
                    lines.append("    return this.delete(path);")
                lines.append("  }")
            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def _generate_exports(self) -> str:
        tag_names = set()
        for path_item in self.paths.values():
            for operation in path_item.values():
                if isinstance(operation, dict):
                    for tag in operation.get("tags", []):
                        tag_names.add(tag.replace("/", "_").replace(" ", ""))

        init_lines = []
        for tag in sorted(tag_names):
            class_name = f"{to_pascal_case(tag)}API"
            attr_name = to_camel_case(tag)
            init_lines.append(f"    this.{attr_name} = new {class_name}(config);")

        attrs = []
        for tag in sorted(tag_names):
            class_name = f"{to_pascal_case(tag)}API"
            attr_name = to_camel_case(tag)
            attrs.append(f"  readonly {attr_name}: {class_name};")

        return f'''// Main SintraPrime client
export class SintraPrimeClient {{
{chr(10).join(attrs)}

  constructor(config: ClientConfig = {{}}) {{
{chr(10).join(init_lines)}
  }}
}}

export default SintraPrimeClient;'''

    def save(self, output_path: str | Path) -> Path:
        code = self.generate()
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(code)
        print(f"✅ TypeScript SDK saved: {path} ({len(code.splitlines())} lines)")
        return path


# ---------------------------------------------------------------------------
# Curl Example Generator
# ---------------------------------------------------------------------------

class CurlExampleGenerator:
    """Generates curl examples for every API endpoint."""

    def __init__(self, spec: dict):
        self.spec = spec
        self.paths = spec.get("paths", {})
        self.servers = spec.get("servers", [{}])
        self.base_url = self.servers[0].get("url", "https://api.example.com") if self.servers else ""

    def generate_all(self) -> list[dict]:
        """Generate curl examples for all endpoints."""
        examples = []
        for path, path_item in self.paths.items():
            for method, operation in path_item.items():
                if not isinstance(operation, dict):
                    continue
                example = self._generate_curl(path, method.upper(), operation)
                examples.append(example)
        return examples

    def _generate_curl(self, path: str, method: str, operation: dict) -> dict:
        params = operation.get("parameters", [])
        request_body = operation.get("requestBody", {})
        op_id = operation.get("operationId", "")
        summary = operation.get("summary", "")
        tags = operation.get("tags", [])

        # Build URL with example path params
        url = self.base_url + path
        for param in [p for p in params if p.get("in") == "path"]:
            example_val = param.get("schema", {}).get("example", f"example_{param['name']}")
            url = url.replace("{" + param["name"] + "}", str(example_val))

        # Add example query params
        query_params = [p for p in params if p.get("in") == "query" and p.get("required")]
        if query_params:
            qp_parts = []
            for p in query_params:
                example_val = p.get("schema", {}).get("example", f"example")
                qp_parts.append(f"{p['name']}={urllib.parse.quote(str(example_val))}")
            url += "?" + "&".join(qp_parts)

        # Build curl command
        lines = [f"# {summary}"]
        lines.append(f"curl -X {method} \\")
        lines.append(f'  "{url}" \\')
        lines.append('  -H "Authorization: Bearer YOUR_API_KEY" \\')
        lines.append('  -H "Content-Type: application/json"')

        if request_body and method in ("POST", "PUT", "PATCH"):
            example_body = self._get_example_body(request_body)
            if example_body:
                body_json = json.dumps(example_body, indent=2)
                # Indent the body for curl
                body_lines = body_json.splitlines()
                lines[-1] += " \\"
                lines.append(f"  -d '{body_lines[0]}")
                for line in body_lines[1:]:
                    lines.append(f"  {line}")
                lines[-1] += "'"

        return {
            "operation_id": op_id,
            "summary": summary,
            "method": method,
            "path": path,
            "tags": tags,
            "curl": "\n".join(lines),
        }

    def _get_example_body(self, request_body: dict) -> dict | None:
        """Extract or generate example request body."""
        content = request_body.get("content", {})
        json_content = content.get("application/json", {})
        if "example" in json_content:
            return json_content["example"]
        schema = json_content.get("schema", {})
        if "$ref" in schema:
            return {"example": "See schema for required fields"}
        return {"key": "value"}

    def save_markdown(self, output_path: str | Path) -> Path:
        """Save curl examples as markdown file."""
        examples = self.generate_all()
        lines = ["# API Curl Examples", "", f"Generated {len(examples)} examples.", ""]

        by_tag: dict[str, list[dict]] = {}
        for ex in examples:
            tags = ex["tags"] or ["Other"]
            for tag in tags:
                by_tag.setdefault(tag, []).append(ex)

        for tag, tag_examples in sorted(by_tag.items()):
            lines.append(f"## {tag}")
            lines.append("")
            for ex in tag_examples:
                lines.append(f"### {ex['summary']}")
                lines.append(f"`{ex['method']} {ex['path']}`")
                lines.append("")
                lines.append("```bash")
                lines.append(ex["curl"])
                lines.append("```")
                lines.append("")

        content = "\n".join(lines)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"✅ Curl examples saved: {path} ({len(examples)} endpoints)")
        return path


# ---------------------------------------------------------------------------
# Convenience: generate all SDKs at once
# ---------------------------------------------------------------------------

def generate_all_sdks(spec: dict | str | Path, output_dir: str | Path = ".") -> dict[str, Path]:
    """Generate Python SDK, TypeScript SDK, and curl examples from OpenAPI spec."""
    spec_data = load_spec(spec)
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results = {}

    # Python SDK
    py_gen = PythonSDKGenerator(spec_data)
    results["python"] = py_gen.save(output_dir / "sintraprime_sdk.py")

    # TypeScript SDK
    ts_gen = TypeScriptSDKGenerator(spec_data)
    results["typescript"] = ts_gen.save(output_dir / "sintraprime_sdk.ts")

    # Curl examples
    curl_gen = CurlExampleGenerator(spec_data)
    results["curl"] = curl_gen.save_markdown(output_dir / "curl_examples.md")

    print(f"\n✅ All SDKs generated in: {output_dir}")
    return results


if __name__ == "__main__":
    # Quick demo with a minimal inline spec
    minimal_spec = {
        "openapi": "3.1.0",
        "info": {"title": "SintraPrime Demo", "version": "2.0.0"},
        "servers": [{"url": "https://api.sintraprime.ikesolutions.org/v2"}],
        "paths": {
            "/legal/case-law/search": {
                "get": {
                    "tags": ["Legal"],
                    "summary": "Search case law",
                    "operationId": "searchCaseLaw",
                    "parameters": [
                        {"name": "query", "in": "query", "required": True, "schema": {"type": "string", "example": "landlord tenant"}},
                    ],
                    "responses": {"200": {"description": "Results"}},
                }
            }
        },
        "components": {
            "schemas": {
                "Error": {"type": "object", "properties": {"code": {"type": "integer"}, "message": {"type": "string"}}},
            }
        },
    }
    generate_all_sdks(minimal_spec, "/tmp/sdk_output")
