"""
Trust Document Generator
========================
Generates properly formatted legal document templates for trust instruments
including revocable living trusts, irrevocable trusts, business trusts,
UCC financing statements, and trust amendments.

LEGAL DISCLAIMER: All documents generated by this module are templates
for educational and informational purposes only. They do not constitute
legal advice and should not be used as final legal documents without
review and revision by a licensed attorney in the applicable jurisdiction.
Laws vary by state and are subject to change. SintraPrime Intelligence
Corp makes no representations regarding the legal sufficiency of these
templates for any particular purpose.
"""

from __future__ import annotations
from datetime import datetime
from typing import List, Dict, Optional, Any
import re


LEGAL_DISCLAIMER = """
================================================================================
LEGAL DISCLAIMER AND NOTICE
================================================================================
This document is a template for educational and informational purposes ONLY.
It does NOT constitute legal advice and should NOT be used as a final legal
document without review, revision, and execution guidance from a licensed
attorney admitted to practice in the applicable jurisdiction(s).

Trust laws vary significantly by state and jurisdiction. Tax implications
depend on specific facts and circumstances. This template may not comply
with all requirements of your jurisdiction.

SintraPrime Intelligence System — For Professional Review Only
================================================================================
"""


def _current_date() -> str:
    """Return the current date formatted for legal documents."""
    return datetime.now().strftime("%B %d, %Y")


def _current_year() -> int:
    return datetime.now().year


class TrustDocumentGenerator:
    """
    Generates full-text trust document templates in proper legal format.
    Documents include recitals, articles, signature blocks, and notary acknowledgments.
    """

    LEGAL_DISCLAIMER = (
        "LEGAL DISCLAIMER: This document is a template for educational and informational "
        "purposes only. It does not constitute legal advice and should not be used as a "
        "final legal document without review by a licensed attorney in the applicable "
        "jurisdiction. Consult an attorney before relying on any template document."
    )

    def generate_revocable_living_trust(
        self,
        grantor_name: str,
        trustee_name: str,
        successor_trustee: str,
        beneficiaries: List[Dict[str, Any]],
        state: str,
    ) -> str:
        """
        Generate a comprehensive Revocable Living Trust document.

        Args:
            grantor_name: Full legal name of the grantor/settlor
            trustee_name: Full legal name of the initial trustee (typically same as grantor)
            successor_trustee: Full legal name of the successor trustee
            beneficiaries: List of dicts with keys: name, relationship, share (percentage)
            state: Governing state for the trust
        """
        beneficiary_text = self._format_beneficiaries(beneficiaries)
        beneficiary_shares = self._format_beneficiary_shares(beneficiaries)

        doc = f"""{LEGAL_DISCLAIMER}

{state.upper()} REVOCABLE LIVING TRUST AGREEMENT

This Revocable Living Trust Agreement (the "Trust Agreement") is made and entered
into this {_current_date()}, by and between {grantor_name} ("Grantor"), and
{trustee_name} ("Trustee").

RECITALS

WHEREAS, the Grantor desires to create a revocable trust for the management of
property and the benefit of the beneficiaries herein described;

WHEREAS, the Trustee has agreed to accept the trust created herein and to
administer the same in accordance with the terms and conditions set forth herein;

WHEREAS, the Grantor intends this Trust Agreement to be revocable and amendable
during the Grantor's lifetime, and to govern the management and distribution of
the trust property during and after the Grantor's life;

NOW, THEREFORE, in consideration of the foregoing recitals and for other good and
valuable consideration, the receipt and sufficiency of which are hereby
acknowledged, the Grantor hereby declares this Trust Agreement upon the following
terms and conditions:

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE I
                        TRUST NAME AND ESTABLISHMENT
═══════════════════════════════════════════════════════════════════════════════

Section 1.1  Name of Trust.  This trust shall be known as the "{grantor_name}
Revocable Living Trust dated {_current_date()}" (the "Trust").

Section 1.2  Trust Property.  The Grantor hereby transfers, assigns, and conveys
to the Trustee the property described in Schedule A attached hereto and incorporated
herein by reference, to be held in trust subject to the terms and conditions of
this Trust Agreement. The Trustee may receive additional property transferred to
the Trust from the Grantor or others at any time. All property so received shall
constitute the trust estate ("Trust Estate") and shall be held, administered, and
distributed in accordance with this Trust Agreement.

Section 1.3  Trust Situs.  This Trust Agreement shall be governed by and construed
in accordance with the laws of the State of {state}, without regard to conflict of
laws provisions.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE II
                         REVOCABILITY AND AMENDMENT
═══════════════════════════════════════════════════════════════════════════════

Section 2.1  Right to Revoke.  During the Grantor's lifetime, the Grantor reserves
the right to revoke this Trust Agreement in whole or in part at any time and from
time to time, without the consent of any beneficiary or Trustee, by a written
instrument signed by the Grantor and delivered to the Trustee.

Section 2.2  Right to Amend.  During the Grantor's lifetime, the Grantor reserves
the right to amend this Trust Agreement in any respect at any time and from time
to time, without the consent of any beneficiary or Trustee, by a written instrument
signed by the Grantor and delivered to the Trustee. No amendment shall increase
the duties or liabilities of the Trustee without the Trustee's written consent.

Section 2.3  Withdrawal of Assets.  During the Grantor's lifetime, the Grantor
reserves the right to withdraw from the Trust any or all of the Trust Estate at
any time and from time to time by written instruction to the Trustee.

Section 2.4  Irrevocability Upon Death.  Upon the death of the Grantor, this Trust
Agreement shall become irrevocable and may not be amended or revoked by any person.

═══════════════════════════════════════════════════════════════════════════════
                             ARTICLE III
                       ADMINISTRATION DURING GRANTOR'S LIFE
═══════════════════════════════════════════════════════════════════════════════

Section 3.1  Distribution During Grantor's Lifetime.  During the Grantor's
lifetime, the Trustee shall hold, manage, invest, and reinvest the Trust Estate
and shall distribute to or for the benefit of the Grantor such amounts of net
income and principal as the Grantor shall from time to time direct.

Section 3.2  Incapacity of Grantor.  If the Grantor is determined to be
incapacitated (as defined in Section 3.3 below), the Trustee shall distribute
such amounts of net income and principal of the Trust Estate as the Trustee, in
its sole and absolute discretion, deems necessary or advisable for the health,
education, maintenance, and support of the Grantor in the Grantor's accustomed
manner of living, and for the health, education, maintenance, and support of
the Grantor's legal dependents.

Section 3.3  Definition of Incapacity.  The Grantor shall be deemed incapacitated
when (a) the Grantor has been adjudicated incompetent by a court of competent
jurisdiction; or (b) the Trustee has received written statements from two (2)
licensed physicians who have examined the Grantor, stating that the Grantor is
unable to manage his or her own financial affairs due to mental or physical
illness, injury, or disability.

Section 3.4  Resumption of Capacity.  If the Grantor shall recover from
incapacity, the Trustee shall resume administering the Trust as directed by the
Grantor.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE IV
                     DISTRIBUTION UPON GRANTOR'S DEATH
═══════════════════════════════════════════════════════════════════════════════

Section 4.1  Payment of Debts and Expenses.  Upon the death of the Grantor, the
Trustee shall pay from the Trust Estate, or may reimburse the Grantor's estate
for, such amounts as the Trustee, in its sole discretion, determines are necessary
to pay: (a) the Grantor's legally enforceable debts; (b) costs of the Grantor's
last illness; (c) funeral and burial expenses; and (d) costs of administering the
Trust Estate and the Grantor's estate.

Section 4.2  Distribution of Trust Estate.  After payment of the items described
in Section 4.1, the Trustee shall distribute the remaining Trust Estate to the
following beneficiaries in the following shares:

{beneficiary_shares}

Section 4.3  Beneficiaries.  The beneficiaries of this Trust are:
{beneficiary_text}

Section 4.4  Contingent Beneficiaries.  If any beneficiary shall predecease the
Grantor, such beneficiary's share shall pass to that beneficiary's then-living
issue, per stirpes. If a beneficiary has no living issue, their share shall be
divided proportionately among the surviving beneficiaries.

Section 4.5  Minor Beneficiaries.  If a distribution is to be made to a minor,
the Trustee may retain such distribution in trust for the minor's benefit until
the minor attains the age of twenty-five (25) years, distributing income and
principal for the minor's health, education, maintenance, and support.

Section 4.6  No-Contest Clause.  If any beneficiary contests this Trust Agreement
or any of its provisions, or commences or maintains any proceeding to contest the
validity of this Trust Agreement, that beneficiary's interest shall thereupon be
reduced to one dollar ($1.00).

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE V
                            TRUSTEE PROVISIONS
═══════════════════════════════════════════════════════════════════════════════

Section 5.1  Successor Trustee.  If {trustee_name} is unable or unwilling to
serve as Trustee, {successor_trustee} shall serve as Successor Trustee.

Section 5.2  Resignation of Trustee.  Any Trustee may resign by giving thirty
(30) days written notice to the Grantor (if living and competent) or to the adult
beneficiaries. Such resignation shall become effective upon the appointment of a
successor trustee or upon the expiration of the notice period, whichever is later.

Section 5.3  Appointment of Successor.  If no Successor Trustee is available or
able to serve, a court of competent jurisdiction in the State of {state} shall
appoint a successor trustee.

Section 5.4  Bond.  No Trustee shall be required to give any bond or surety for
the faithful performance of its duties under this Trust Agreement.

Section 5.5  Compensation.  The Trustee shall be entitled to reasonable
compensation for services rendered, which shall not exceed the standard schedule
of fees charged by corporate trustees in the State of {state} for similar services.

Section 5.6  Trustee Liability.  No Trustee shall be liable for any error in
judgment or any act or omission hereunder, except for willful misconduct or gross
negligence. No Trustee shall be required to take any action that would expose the
Trustee to personal liability without adequate indemnification.

Section 5.7  Co-Trustee.  The Grantor may appoint a Co-Trustee at any time by
written instrument. Co-Trustees must act unanimously unless otherwise provided.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE VI
                           POWERS OF THE TRUSTEE
═══════════════════════════════════════════════════════════════════════════════

The Trustee shall have all powers granted by the laws of the State of {state}
to trustees, and in addition, the following specific powers, all of which are to
be exercised in a fiduciary capacity:

Section 6.1  Investment Powers.  To invest and reinvest the Trust Estate in any
property, real or personal, including without limitation: stocks, bonds, mutual
funds, exchange-traded funds, real estate investment trusts, limited partnerships,
limited liability companies, hedge funds, private equity funds, precious metals,
cryptocurrencies, and any other investments as the Trustee deems prudent.

Section 6.2  Real Estate Powers.  To purchase, hold, sell, exchange, lease,
mortgage, improve, and manage real property; to grant or acquire options on real
property; and to partition any real estate held by the Trust.

Section 6.3  Business Powers.  To continue, operate, reorganize, sell, or
liquidate any business interest held by the Trust; to incorporate, form LLCs, or
take other organizational steps with respect to business interests.

Section 6.4  Borrowing.  To borrow money for any trust purpose from any source,
including from a Trustee in its individual capacity, at prevailing rates, and to
mortgage or pledge Trust assets as security.

Section 6.5  Delegation.  To employ attorneys, accountants, investment advisors,
and other agents; to delegate investment and other ministerial functions subject
to the Trustee's ongoing duty to monitor.

Section 6.6  Distribution Powers.  To make distributions in cash or in kind, or
partly in each; to allocate different assets to different beneficiaries without
regard to the income tax basis of the assets.

Section 6.7  Tax Elections.  To make all tax elections available to the Trustee
or the estate, including elections under the Internal Revenue Code.

Section 6.8  Prudent Investor Standard.  In exercising investment powers, the
Trustee shall comply with the Prudent Investor Act as adopted in {state} or, if
not adopted, the prudent investor standard under applicable law.

═══════════════════════════════════════════════════════════════════════════════
                             ARTICLE VII
                        SPENDTHRIFT PROVISIONS
═══════════════════════════════════════════════════════════════════════════════

Section 7.1  Spendthrift Clause.  No interest of any beneficiary in this Trust,
whether in the income or principal thereof, shall be alienated, transferred,
assigned, pledged, or in any manner encumbered by such beneficiary, nor shall
such interest be subject to levy, execution, attachment, garnishment, or claims of
creditors of any beneficiary, until such time as the interest is actually paid
to or vested in such beneficiary.

Section 7.2  Trustee Discretion.  If any creditor of a beneficiary attempts to
attach or garnish any trust interest, the Trustee may, in its discretion, reduce
or withhold distributions from such beneficiary and apply such amounts directly
for the health, education, maintenance, and support of such beneficiary.

═══════════════════════════════════════════════════════════════════════════════
                             ARTICLE VIII
                        GENERAL PROVISIONS
═══════════════════════════════════════════════════════════════════════════════

Section 8.1  Governing Law.  This Trust Agreement and all questions concerning its
validity, construction, and administration shall be governed by the laws of the
State of {state}.

Section 8.2  Severability.  If any provision of this Trust Agreement is held to
be invalid, illegal, or unenforceable, such provision shall be deemed modified to
the minimum extent necessary to make it valid, legal, and enforceable, and the
validity and enforceability of the remaining provisions shall not in any way be
affected.

Section 8.3  Headings.  Article and section headings are for convenience of
reference only and shall not affect the interpretation of this Trust Agreement.

Section 8.4  Counterparts.  This Trust Agreement may be executed in one or more
counterparts, each of which shall be deemed an original.

Section 8.5  Entire Agreement.  This Trust Agreement, together with any schedules
attached hereto, constitutes the entire agreement of the parties with respect to
the subject matter hereof.

Section 8.6  Fiduciary Duty.  The Trustee shall at all times act in accordance
with the highest fiduciary duties owed to the beneficiaries of this Trust,
including duties of loyalty, impartiality, prudence, and full disclosure.

═══════════════════════════════════════════════════════════════════════════════
                          SIGNATURE PAGE
═══════════════════════════════════════════════════════════════════════════════

IN WITNESS WHEREOF, the parties have executed this Revocable Living Trust
Agreement as of the date first written above.

GRANTOR:

_______________________________________     Date: _______________
{grantor_name}
Grantor / Settlor


TRUSTEE:

_______________________________________     Date: _______________
{trustee_name}
Initial Trustee


SUCCESSOR TRUSTEE ACKNOWLEDGMENT:

I, {successor_trustee}, acknowledge that I have received a copy of this
Trust Agreement and agree to serve as Successor Trustee when called upon
to do so pursuant to its terms.

_______________________________________     Date: _______________
{successor_trustee}
Successor Trustee


═══════════════════════════════════════════════════════════════════════════════
                        NOTARY ACKNOWLEDGMENT — GRANTOR
═══════════════════════════════════════════════════════════════════════════════

STATE OF {state.upper()}
COUNTY OF ____________________

On this _______ day of _________________, {_current_year()}, before me, a Notary
Public in and for said County and State, personally appeared {grantor_name},
to me known to be the person whose name is subscribed to the foregoing instrument,
and acknowledged that he/she executed the same as his/her free and voluntary act
and deed, for the uses and purposes therein set forth.

_______________________________________
Notary Public, State of {state}
My Commission Expires: _______________
[SEAL]


═══════════════════════════════════════════════════════════════════════════════
                              SCHEDULE A
                    INITIAL TRUST PROPERTY
═══════════════════════════════════════════════════════════════════════════════

The following property is hereby transferred to and shall constitute the initial
Trust Estate:

1. [$1.00 (One Dollar) and such other property as may from time to time be
   transferred to the Trustee in accordance with this Trust Agreement]

2. [LIST ADDITIONAL PROPERTY HERE — Real estate (with full legal descriptions),
   account numbers, brokerage accounts, business interests, etc.]

NOTE: Proper funding of this trust requires the re-titling of assets into the
name of the Trustee (e.g., "John Smith, as Trustee of the John Smith Revocable
Living Trust dated ___________"). Failure to fund the trust defeats the
probate avoidance purpose.

═══════════════════════════════════════════════════════════════════════════════

{LEGAL_DISCLAIMER}
"""
        return doc

    def generate_irrevocable_asset_protection_trust(
        self,
        grantor_name: str,
        trustee_name: str,
        beneficiaries: List[Dict[str, Any]],
        jurisdiction: str,
        assets: List[str],
    ) -> str:
        """Generate an Irrevocable Asset Protection Trust document."""
        beneficiary_text = self._format_beneficiaries(beneficiaries)
        assets_text = "\n".join(f"  {i+1}. {a}" for i, a in enumerate(assets)) if assets else "  [To be listed in Schedule A]"
        beneficiary_names = ", ".join(b if isinstance(b, str) else b.get("name", "") for b in beneficiaries)

        doc = f"""{LEGAL_DISCLAIMER}

{jurisdiction.upper()} IRREVOCABLE ASSET PROTECTION TRUST AGREEMENT

This Irrevocable Asset Protection Trust Agreement (the "Trust Agreement") is
entered into as of {_current_date()}, by {grantor_name} ("Grantor"), and
{trustee_name} ("Trustee").

RECITALS

WHEREAS, the Grantor desires to establish an irrevocable trust for asset
protection, estate planning, and the benefit of the Grantor's family members;

WHEREAS, the Grantor, by creating this irrevocable trust, is permanently
relinquishing all ownership interests and control over the Trust Estate except
as expressly permitted herein;

WHEREAS, the Trustee has agreed to hold and administer the Trust Estate in
accordance with the terms hereof;

NOW, THEREFORE, for good and valuable consideration, the Grantor hereby
irrevocably transfers the property listed in Schedule A to the Trustee, to be
held in trust upon the following terms and conditions:

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE I
                   TRUST NAME, IRREVOCABILITY, AND PROPERTY
═══════════════════════════════════════════════════════════════════════════════

Section 1.1  Name.  This Trust shall be known as the "{grantor_name} Irrevocable
Asset Protection Trust dated {_current_date()}."

Section 1.2  Irrevocability.  THIS TRUST IS IRREVOCABLE AND MAY NOT BE REVOKED,
ALTERED, OR AMENDED IN ANY RESPECT BY THE GRANTOR OR ANY OTHER PERSON, except
as expressly permitted by applicable law (including modification by unanimous
beneficiary consent under UTC §411 if applicable, or judicial modification for
changed circumstances).

Section 1.3  Governing Law.  This Trust shall be governed by the laws of
{jurisdiction}, which has adopted the following relevant statutes:
[Insert applicable asset protection trust statute reference for {jurisdiction}].

Section 1.4  Trust Situs.  The situs of this Trust shall be {jurisdiction}.
The Trust shall be administered in {jurisdiction}.

Section 1.5  Initial Trust Property.  The Grantor hereby transfers and assigns
to the Trustee the following assets, free and clear of all conditions except
as set forth herein:

{assets_text}

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE II
                       BENEFICIARIES AND DISTRIBUTIONS
═══════════════════════════════════════════════════════════════════════════════

Section 2.1  Beneficiaries.  The beneficiaries of this Trust are:
{beneficiary_text}

Section 2.2  Grantor as Discretionary Beneficiary.  The Grantor ({grantor_name})
may be included as a DISCRETIONARY BENEFICIARY of the Trust, subject to the
sole and absolute discretion of the Trustee. [NOTE: Whether the Grantor may be
a beneficiary depends on jurisdiction — self-settled trusts are permitted in DAPT
states and offshore jurisdictions. Consult attorney to confirm applicability in
{jurisdiction}.]

Section 2.3  Discretionary Distributions.  The Trustee shall have the sole and
absolute discretion to distribute or withhold income and/or principal of the Trust
Estate for the health, education, maintenance, and support of the beneficiaries.
No beneficiary shall have any right to compel any distribution.

Section 2.4  Spendthrift Clause.  The interest of each beneficiary in this Trust
is subject to a spendthrift restriction. No beneficiary may assign, transfer,
pledge, or otherwise encumber his or her interest in the Trust. No creditor of
any beneficiary shall have any claim against any interest in the Trust Estate
before it is distributed to the beneficiary.

Section 2.5  Exception Creditors.  Notwithstanding the spendthrift provisions,
the following creditors may be entitled to reach trust assets in certain
jurisdictions: (a) claims for child support or alimony; (b) claims of government
entities under specific statutory authority. The Grantor and Trustee acknowledge
this limitation.

Section 2.6  Protection Period.  Trust assets shall be protected from the
Grantor's creditors pursuant to the laws of {jurisdiction} for the maximum period
permitted by law, provided the transfer was not made with actual intent to defraud
existing creditors.

Section 2.7  No Assignment.  The Trustee shall have no duty to distribute to any
beneficiary whose interest has been purported to be assigned, transferred, or
pledged to a creditor. The Trustee shall treat such purported assignment as void.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE III
                        TRUSTEE AND ADMINISTRATION
═══════════════════════════════════════════════════════════════════════════════

Section 3.1  Independent Trustee.  The Trustee shall be an independent trustee
having no beneficial interest in the Trust. The Grantor shall not serve as Trustee
or Co-Trustee of this Trust. [Note: This independence requirement is critical for
asset protection trust validity.]

Section 3.2  Trustee Powers.  The Trustee shall have all powers granted to
trustees under the laws of {jurisdiction}, including:
  (a) Investment and reinvestment of Trust assets;
  (b) Sale, exchange, lease, or encumbrance of Trust property;
  (c) Borrowing funds on behalf of the Trust;
  (d) Employment of agents, advisors, and professionals;
  (e) Making distributions in cash or in kind;
  (f) Holding assets in nominee name;
  (g) Maintaining bank and brokerage accounts;
  (h) Engaging in any lawful business activity.

Section 3.3  Protector.  The following person is appointed as Trust Protector:
[NAME OF PROTECTOR]. The Protector shall have the power to:
  (a) Remove and replace the Trustee;
  (b) Add or remove discretionary beneficiaries;
  (c) Amend administrative provisions of the Trust;
  (d) Change the situs and governing law of the Trust;
  (e) Veto any distribution proposed by the Trustee.

Section 3.4  Certification of Independence.  The Trustee hereby certifies that
it is independent of the Grantor and has no obligation, legally or otherwise,
to act at the direction of the Grantor with respect to distributions or
investment decisions.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE IV
                         FRAUDULENT TRANSFER ACKNOWLEDGMENT
═══════════════════════════════════════════════════════════════════════════════

Section 4.1  Solvency Representation.  The Grantor represents and warrants that:
  (a) The Grantor is solvent as of the date of this Trust Agreement;
  (b) The Grantor's transfer of assets to this Trust does not render the Grantor
      insolvent or unable to pay debts as they become due;
  (c) The Grantor is not transferring assets with actual intent to hinder, delay,
      or defraud any existing creditor;
  (d) The Grantor has adequate assets remaining outside this Trust to satisfy
      all known, existing, and reasonably foreseeable creditor claims.

Section 4.2  Fraudulent Transfer Risk.  The parties acknowledge that if any
transfer to this Trust is determined to be a fraudulent transfer under applicable
law (including the Uniform Voidable Transactions Act), such transfer may be
voided by a court and the trust asset(s) may be made available to creditors.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE V
                           TERM AND TERMINATION
═══════════════════════════════════════════════════════════════════════════════

Section 5.1  Trust Term.  This Trust shall continue until the earliest of:
  (a) The date on which all Trust assets have been distributed;
  (b) Twenty-one (21) years after the death of the last surviving beneficiary
      who was living at the creation of this Trust (unless {jurisdiction} permits
      a longer period or has abolished the Rule Against Perpetuities); or
  (c) Such earlier date as the Trustee, with the consent of all then-living
      beneficiaries, determines to terminate the Trust.

Section 5.2  Distribution on Termination.  Upon termination, the Trustee shall
distribute all remaining Trust assets to the then-living beneficiaries in equal
shares, or as the Trustee shall determine in its discretion if amounts are unequal.

═══════════════════════════════════════════════════════════════════════════════
                          SIGNATURE AND EXECUTION
═══════════════════════════════════════════════════════════════════════════════

IN WITNESS WHEREOF, the undersigned have executed this Irrevocable Asset
Protection Trust Agreement as of the date first written above.

GRANTOR:

_______________________________________     Date: _______________
{grantor_name}, Grantor

TRUSTEE ACCEPTANCE:
I, {trustee_name}, hereby accept the trusts created by this Trust Agreement
and agree to administer them in accordance with its terms.

_______________________________________     Date: _______________
{trustee_name}, Trustee


STATE OF {jurisdiction.upper()}
COUNTY OF ____________________

Before me, a Notary Public, personally appeared {grantor_name} and {trustee_name},
known to me, who acknowledged executing the foregoing instrument for the purposes
stated therein.

_______________________________________
Notary Public
My Commission Expires: _______________
[SEAL]


═══════════════════════════════════════════════════════════════════════════════
                              SCHEDULE A
                      PROPERTY TRANSFERRED TO TRUST
═══════════════════════════════════════════════════════════════════════════════

{assets_text}

[ATTACH ADDITIONAL PAGES AS NEEDED]

{LEGAL_DISCLAIMER}
"""
        return doc

    def generate_business_trust(
        self,
        trust_name: str,
        trustees: List[str],
        beneficiaries: List[Dict[str, Any]],
        purpose: str,
        state: str,
    ) -> str:
        """Generate a Business Trust / Massachusetts Business Trust document."""
        trustees_text = "\n".join(f"  - {t}" for t in trustees)
        beneficiary_text = self._format_beneficiaries(beneficiaries)

        doc = f"""{LEGAL_DISCLAIMER}

BUSINESS TRUST DECLARATION
(Massachusetts Business Trust / Statutory Business Trust)

This Declaration of Business Trust (the "Declaration") is executed and delivered
as of {_current_date()}, by the Trustees named herein.

DECLARATION

The undersigned Trustees hereby declare that they hold and will hold all property
transferred to them as Trustees under this Declaration, IN TRUST, for the purposes
and on the terms set forth herein.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE I
                           TRUST NAME AND PURPOSE
═══════════════════════════════════════════════════════════════════════════════

Section 1.1  Name.  The name of this trust is: {trust_name}

Section 1.2  Business Purpose.  This Trust is organized and shall be operated
exclusively for the following business purposes:
{purpose}

Additional lawful purposes incidental or reasonably related to the foregoing.

Section 1.3  Governing Law.  This Trust is created under and governed by the laws
of the State of {state}. The Trustees intend this Trust to be treated as a
business trust (or statutory business trust if applicable under {state} law) and
not as a general partnership, corporation, or other form of organization.

Section 1.4  Principal Office.  The principal place of business of this Trust
shall be at such location as the Trustees shall from time to time determine.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE II
                     BENEFICIAL INTERESTS AND CERTIFICATES
═══════════════════════════════════════════════════════════════════════════════

Section 2.1  Beneficial Interests.  The beneficial interests in this Trust are
divided into [NUMBER] units of beneficial interest (the "Units"), all of equal
value. The Trustees may issue additional Units with the consent of holders of a
majority of outstanding Units.

Section 2.2  Certificates.  The Trustees shall issue Certificates of Beneficial
Interest (the "Certificates") representing the Units. Certificates shall be in
such form as the Trustees determine, shall be signed by at least one Trustee,
and shall be transferable as set forth in Article IV.

Section 2.3  Register of Beneficial Owners.  The Trustees shall maintain a
register of all holders of beneficial interests ("Beneficial Owners"). The
register shall contain the name, address, and Units held by each Beneficial Owner.

Section 2.4  Initial Beneficial Owners.  The initial Beneficial Owners are:
{beneficiary_text}

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE III
                              TRUSTEES
═══════════════════════════════════════════════════════════════════════════════

Section 3.1  Initial Trustees.  The initial Trustees of this Trust are:
{trustees_text}

Section 3.2  Number of Trustees.  The number of Trustees shall be not less than
one (1) and not more than five (5), as determined from time to time by vote of
the Beneficial Owners holding a majority of Units.

Section 3.3  Election of Trustees.  Trustees shall be elected by the Beneficial
Owners at the annual meeting of Beneficial Owners.

Section 3.4  Trustee Powers.  The Trustees shall have full and exclusive authority
to manage the business and affairs of the Trust, including:
  (a) Buying, selling, leasing, or encumbering real and personal property;
  (b) Entering into contracts on behalf of the Trust;
  (c) Employing agents, employees, and advisors;
  (d) Borrowing money and issuing evidences of indebtedness;
  (e) Investing Trust funds in any lawful manner;
  (f) Distributing Trust income and principal to Beneficial Owners;
  (g) Maintaining bank accounts and custodial accounts;
  (h) Filing tax returns and making tax elections;
  (i) Instituting or defending legal proceedings on behalf of the Trust.

Section 3.5  Trustee Liability.  No Trustee shall be personally liable for any
debt, obligation, or liability of the Trust, except for such Trustee's own fraud,
willful misconduct, or gross negligence. The Trust Estate shall be the sole source
of payment for all Trust obligations.

Section 3.6  Trustee Compensation.  Each Trustee shall receive such compensation
as the Beneficial Owners shall determine from time to time.

Section 3.7  Meetings of Trustees.  The Trustees shall meet at such times as they
determine. Action may be taken by unanimous written consent without a meeting.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE IV
                    TRANSFER OF BENEFICIAL INTERESTS
═══════════════════════════════════════════════════════════════════════════════

Section 4.1  Transferability.  Units of beneficial interest shall be freely
transferable, subject to compliance with applicable securities laws. No transfer
shall be valid unless recorded in the register maintained by the Trustees.

Section 4.2  Securities Law Compliance.  The Trustees and Beneficial Owners
acknowledge that Units may constitute "securities" under applicable federal and
state securities laws if the Trust has multiple investors and the efforts of others
are expected to generate profits. All transfers and issuances shall comply with
applicable securities laws.

Section 4.3  Right of First Refusal.  Before any Beneficial Owner may transfer
Units to a non-Beneficial Owner, the other Beneficial Owners shall have a right
of first refusal to purchase such Units at the offered price and on the same terms.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE V
                         DISTRIBUTIONS AND INCOME
═══════════════════════════════════════════════════════════════════════════════

Section 5.1  Distributions.  The Trustees shall distribute net income to
Beneficial Owners at least annually, in proportion to their Units held, unless
the Trustees determine to reinvest such income.

Section 5.2  Return of Capital.  The Trustees may distribute principal of the
Trust Estate to Beneficial Owners when the Trustees deem it appropriate.

Section 5.3  Tax Elections.  The Trustees shall make such tax elections as they
deem appropriate, including elections as to the classification of the Trust for
federal income tax purposes.

═══════════════════════════════════════════════════════════════════════════════
                              ARTICLE VI
                          TERM AND DISSOLUTION
═══════════════════════════════════════════════════════════════════════════════

Section 6.1  Term.  This Trust shall continue until dissolved pursuant to this
Article VI.

Section 6.2  Dissolution.  This Trust may be dissolved by:
  (a) Vote of holders of two-thirds (2/3) of the outstanding Units;
  (b) Sale or disposition of all Trust assets;
  (c) Judicial dissolution; or
  (d) Such other events as are required by applicable law.

Section 6.3  Winding Up.  Upon dissolution, the Trustees shall wind up the
Trust's business, pay all debts and obligations, and distribute remaining assets
to Beneficial Owners in proportion to their Units.

═══════════════════════════════════════════════════════════════════════════════
                         EXECUTION BY TRUSTEES
═══════════════════════════════════════════════════════════════════════════════

IN WITNESS WHEREOF, the undersigned Trustees have executed this Declaration of
Business Trust as of the date first written above.

TRUSTEES:

_______________________________________     Date: _______________
[Trustee Name], Trustee

_______________________________________     Date: _______________
[Trustee Name], Trustee


STATE OF {state.upper()}         )
COUNTY OF ____________________   )

Acknowledged before me this _____ day of _________________, {_current_year()}.

_______________________________________
Notary Public
My Commission Expires: _______________
[SEAL]

{LEGAL_DISCLAIMER}
"""
        return doc

    def generate_ucc_financing_statement(
        self,
        debtor_name: str,
        secured_party: str,
        collateral_description: str,
        filing_state: str,
    ) -> str:
        """Generate a UCC-1 Financing Statement."""
        doc = f"""{LEGAL_DISCLAIMER}

═══════════════════════════════════════════════════════════════════════════════
           UCC FINANCING STATEMENT — FORM UCC1 (Preparation Worksheet)
═══════════════════════════════════════════════════════════════════════════════

FILING INFORMATION:
State of Filing:          {filing_state}
Date Prepared:            {_current_date()}
File In:                  Office of the Secretary of State, {filing_state}
Effective Period:         5 years from filing date
                         (Continue within last 6 months of 5-year period)
Filing Fee:               [Check current fee schedule for {filing_state}]

═══════════════════════════════════════════════════════════════════════════════
SECTION 1 — DEBTOR INFORMATION
═══════════════════════════════════════════════════════════════════════════════

1a. DEBTOR'S EXACT LEGAL NAME — DO NOT ABBREVIATE
    (For an individual: Last Name, First Name, Middle Name)
    (For an organization: Exact registered name)

    Debtor Name:          {debtor_name}

1b. MAILING ADDRESS:      _________________________________________________
    City:                 _________________ State: ____ Postal Code: _______
    Country:              _______________________

1c. TYPE OF ORGANIZATION (check one):
    [ ] Individual
    [ ] Corporation
    [ ] LLC
    [ ] Partnership
    [ ] Other: _______________

1d. JURISDICTION OF ORGANIZATION (if applicable): _________________________
1e. ORGANIZATIONAL ID #: _________________ [ ] None

═══════════════════════════════════════════════════════════════════════════════
SECTION 2 — SECURED PARTY INFORMATION
═══════════════════════════════════════════════════════════════════════════════

2a. SECURED PARTY'S NAME:
    {secured_party}

2b. MAILING ADDRESS:      _________________________________________________
    City:                 _________________ State: ____ Postal Code: _______
    Country:              _______________________

═══════════════════════════════════════════════════════════════════════════════
SECTION 3 — COLLATERAL
═══════════════════════════════════════════════════════════════════════════════

3. COLLATERAL: This financing statement covers the following collateral:

{collateral_description}

[NOTE: Collateral description must sufficiently identify the collateral.
UCC §9-108. Descriptions by item or type, or by category, or by formula, or
by any other method, if the identity of the collateral is objectively determinable,
are sufficient. "All assets" or "all personal property" is sufficient under
§9-504 for financing statements.]

□  Check only if collateral is held in a Trust or is being administered by a
   Decedent's Personal Representative — Debtor is a Trustee.

□  Check only if applicable and check ONE of the following:
   □  PUBLIC-FINANCE TRANSACTION
   □  MANUFACTURED-HOME TRANSACTION
   □  A DEBTOR IS A TRANSMITTING UTILITY

═══════════════════════════════════════════════════════════════════════════════
SECTION 4 — OPTIONAL ADDITIONAL INFORMATION
═══════════════════════════════════════════════════════════════════════════════

4a. Alternative Debtor Name (if any): _____________________________________
4b. Additional Collateral (if any): _______________________________________
4c. Fixture filing: [ ] Yes — Real Property Description Attached
4d. Product of Collateral: [ ] Yes
4e. Assigned to:  [ ] Yes — Assignee information attached

═══════════════════════════════════════════════════════════════════════════════
FILING CHECKLIST AND INSTRUCTIONS
═══════════════════════════════════════════════════════════════════════════════

FILING LOCATION RULES (UCC §9-301 through §9-307):
  • Individual debtor: File in state where individual RESIDES
  • Registered organization (corp/LLC): File in state of ORGANIZATION
  • Unregistered organization: File where chief executive office is located
  • Registered organization = name on file with state agency

COLLATERAL DESCRIPTION TIPS:
  • Be specific — "all equipment" is acceptable
  • Include serial numbers for titled goods if possible
  • For accounts receivable: "All accounts, including all accounts receivable,
    contract rights, general intangibles, instruments, and chattel paper,
    whether now existing or hereafter arising"
  • For intellectual property: "All patents, trademarks, copyrights, trade
    secrets, and all applications and registrations thereof"

SEARCH BEFORE FILING:
  Always conduct a UCC search in the debtor's jurisdiction before filing to
  identify existing liens. Priority generally follows first-to-file-or-perfect
  (UCC §9-322).

CONTINUATION:
  File UCC-3 Continuation within the SIX MONTHS before the 5-year lapse date.
  Failure to continue will terminate the filing and all priority is lost.

AMENDMENT — USE UCC-3 FOR:
  • Continuation (extend 5-year period)
  • Termination (release lien)
  • Amendment (change debtor name, secured party name, or collateral)
  • Assignment (assign secured party's rights to another)

═══════════════════════════════════════════════════════════════════════════════
SECURED PARTY SIGNATURE (for certain filings)
═══════════════════════════════════════════════════════════════════════════════

AUTHORIZED SIGNATURE:

_______________________________________     Date: _______________
{secured_party}, Secured Party
(Authorized Representative)

[NOTE: Many states accept electronic filing. Check {filing_state} Secretary
of State website for online filing options. Most states do not require a
signature on the UCC-1, but the secured party authorizes the filing.]

═══════════════════════════════════════════════════════════════════════════════

{LEGAL_DISCLAIMER}
"""
        return doc

    def generate_trust_amendment(
        self,
        original_trust_name: str,
        grantor_name: str,
        amendment_details: List[str],
    ) -> str:
        """Generate a Trust Amendment document."""
        amendment_text = "\n\n".join(
            f"AMENDMENT {i+1}:\n{detail}"
            for i, detail in enumerate(amendment_details)
        )
        doc = f"""{LEGAL_DISCLAIMER}

AMENDMENT TO TRUST AGREEMENT

This Amendment to Trust Agreement (this "Amendment") is executed as of
{_current_date()}, by {grantor_name} ("Grantor").

RECITALS

WHEREAS, the Grantor created the {original_trust_name} (the "Trust") pursuant
to a Trust Agreement dated [ORIGINAL DATE];

WHEREAS, the Grantor reserved the right to amend the Trust during the Grantor's
lifetime;

WHEREAS, the Grantor desires to amend certain provisions of the Trust Agreement
as set forth herein;

NOW, THEREFORE, the Grantor hereby amends the Trust Agreement as follows:

═══════════════════════════════════════════════════════════════════════════════
                         AMENDMENTS
═══════════════════════════════════════════════════════════════════════════════

{amendment_text}

═══════════════════════════════════════════════════════════════════════════════
                         GENERAL PROVISIONS
═══════════════════════════════════════════════════════════════════════════════

1. Except as modified by this Amendment, all terms and provisions of the Trust
   Agreement remain in full force and effect without modification.

2. In the event of any conflict between the terms of this Amendment and the
   original Trust Agreement (or any prior amendment), the terms of this
   Amendment shall control.

3. This Amendment shall be construed as part of and read together with the
   original Trust Agreement.

4. Capitalized terms used but not defined herein have the meanings given to
   them in the original Trust Agreement.

═══════════════════════════════════════════════════════════════════════════════
                              SIGNATURE
═══════════════════════════════════════════════════════════════════════════════

IN WITNESS WHEREOF, the Grantor has executed this Amendment as of the date
first written above.

GRANTOR:

_______________________________________     Date: _______________
{grantor_name}, Grantor


STATE OF ____________________________   )
                                        )  ss.
COUNTY OF ___________________________   )

On this _______ day of _________________, {_current_year()}, before me, the
undersigned Notary Public, personally appeared {grantor_name}, to me known
to be the person described in and who executed the foregoing Amendment to
Trust Agreement, and acknowledged that he/she executed the same as his/her
free and voluntary act and deed.

_______________________________________
Notary Public
My Commission Expires: _______________
[SEAL]

{LEGAL_DISCLAIMER}
"""
        return doc

    # ── Private Helpers ──────────────────────────────────────────────────────

    def _format_beneficiaries(self, beneficiaries: List[Any]) -> str:
        if not beneficiaries:
            return "  [No beneficiaries specified]"
        lines = []
        for b in beneficiaries:
            if isinstance(b, str):
                lines.append(f"  - {b}")
            else:
                name = b.get("name", "[Name]")
                rel = b.get("relationship", "")
                share = b.get("share", "")
                line = f"  - {name}"
                if rel:
                    line += f" ({rel})"
                if share:
                    line += f" — {share}%"
                lines.append(line)
        return "\n".join(lines)

    def _format_beneficiary_shares(self, beneficiaries: List[Any]) -> str:
        if not beneficiaries:
            return "  [Distribution schedule to be specified]"
        lines = []
        n = len(beneficiaries)
        equal_share = round(100 / n, 2) if n > 0 else 100
        for b in beneficiaries:
            if isinstance(b, str):
                lines.append(f"  {b}: {equal_share}% of the Trust Estate")
            else:
                name = b.get("name", "[Name]")
                share = b.get("share", equal_share)
                lines.append(f"  {name}: {share}% of the Trust Estate")
        return "\n".join(lines)
