"""Phase 17D — Windows Deployment Preparation.

Generates all artifacts needed to deploy SintraPrime as a native Windows
application: PowerShell setup script, PyInstaller spec, NSIS/WiX installer
manifest, system tray configuration, auto-updater config, and registry entries.
"""
from __future__ import annotations

import os
import uuid
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Optional


# ─────────────────────────────────────────────────────────────────────────────
# Models
# ─────────────────────────────────────────────────────────────────────────────

class InstallerType(str, Enum):
    NSIS = "nsis"
    WIX = "wix"
    INNO = "inno"


class DeploymentTarget(str, Enum):
    SINGLE_USER = "single_user"
    ALL_USERS = "all_users"
    PORTABLE = "portable"


@dataclass
class AppConfig:
    name: str = "SintraPrime"
    version: str = "1.0.0"
    author: str = "SintraPrime AI"
    description: str = "Autonomous Legal AI Platform"
    icon_path: str = "assets/sintra_icon.ico"
    entry_point: str = "sintra_main.py"
    install_dir: str = r"C:\Program Files\SintraPrime"
    data_dir: str = r"%APPDATA%\SintraPrime"
    python_version: str = "3.11"
    target: DeploymentTarget = DeploymentTarget.ALL_USERS
    installer_type: InstallerType = InstallerType.NSIS
    enable_auto_update: bool = True
    enable_system_tray: bool = True
    enable_startup: bool = False


@dataclass
class DeploymentArtifact:
    artifact_id: str
    artifact_type: str
    filename: str
    content: str
    description: str
    size_bytes: int = 0

    def __post_init__(self):
        self.size_bytes = len(self.content.encode("utf-8"))


@dataclass
class DeploymentBundle:
    bundle_id: str
    app_config: AppConfig
    artifacts: List[DeploymentArtifact] = field(default_factory=list)
    created_at: float = field(default_factory=lambda: __import__("time").time())

    def get_artifact(self, artifact_type: str) -> Optional[DeploymentArtifact]:
        for a in self.artifacts:
            if a.artifact_type == artifact_type:
                return a
        return None

    def artifact_types(self) -> List[str]:
        return [a.artifact_type for a in self.artifacts]

    def total_size_bytes(self) -> int:
        return sum(a.size_bytes for a in self.artifacts)

    def save_all(self, output_dir: str) -> List[str]:
        """Write all artifacts to disk and return file paths."""
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        paths = []
        for artifact in self.artifacts:
            p = out / artifact.filename
            p.write_text(artifact.content, encoding="utf-8")
            paths.append(str(p))
        return paths


# ─────────────────────────────────────────────────────────────────────────────
# Generator classes
# ─────────────────────────────────────────────────────────────────────────────

class PowerShellSetupGenerator:
    """Generates the PowerShell setup/install script."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        startup_block = ""
        if cfg.enable_startup:
            startup_block = f"""
# Add to Windows startup
$startupKey = "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run"
Set-ItemProperty -Path $startupKey -Name "{cfg.name}" -Value '"{cfg.install_dir}\\{cfg.name}.exe"'
Write-Host "  Added to startup" -ForegroundColor Green
"""
        content = f"""#Requires -RunAsAdministrator
<#
.SYNOPSIS
    {cfg.name} v{cfg.version} — Windows Setup Script
.DESCRIPTION
    {cfg.description}
    Generated by SintraPrime Windows Deployer
.AUTHOR
    {cfg.author}
#>

param(
    [string]$InstallDir = "{cfg.install_dir}",
    [string]$DataDir = "$env:APPDATA\\{cfg.name}",
    [switch]$Silent,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function Write-Step {{
    param([string]$Message)
    if (-not $Silent) {{ Write-Host "  >> $Message" -ForegroundColor Cyan }}
}}

function Test-PythonVersion {{
    try {{
        $ver = (python --version 2>&1).ToString()
        return $ver -match "Python {cfg.python_version}"
    }} catch {{ return $false }}
}}

# ── Uninstall mode ────────────────────────────────────────────────────────────
if ($Uninstall) {{
    Write-Host "Uninstalling {cfg.name}..." -ForegroundColor Yellow
    if (Test-Path $InstallDir) {{
        Remove-Item -Recurse -Force $InstallDir
        Write-Step "Removed installation directory"
    }}
    if (Test-Path $DataDir) {{
        $confirm = Read-Host "Remove user data? (y/N)"
        if ($confirm -eq "y") {{ Remove-Item -Recurse -Force $DataDir }}
    }}
    # Remove registry entries
    Remove-ItemProperty -Path "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" -ErrorAction SilentlyContinue
    Write-Host "{cfg.name} uninstalled successfully." -ForegroundColor Green
    exit 0
}}

# ── Install mode ──────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ╔══════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "  ║   {cfg.name} v{cfg.version} Installer         ║" -ForegroundColor Magenta
Write-Host "  ╚══════════════════════════════════════╝" -ForegroundColor Magenta
Write-Host ""

# Check Python
Write-Step "Checking Python {cfg.python_version}..."
if (-not (Test-PythonVersion)) {{
    Write-Host "Python {cfg.python_version} not found. Downloading..." -ForegroundColor Yellow
    $pyUrl = "https://www.python.org/ftp/python/{cfg.python_version}.0/python-{cfg.python_version}.0-amd64.exe"
    $pyInstaller = "$env:TEMP\\python_setup.exe"
    Invoke-WebRequest -Uri $pyUrl -OutFile $pyInstaller
    Start-Process -Wait -FilePath $pyInstaller -ArgumentList "/quiet", "InstallAllUsers=1", "PrependPath=1"
    Remove-Item $pyInstaller
}}

# Create directories
Write-Step "Creating directories..."
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
New-Item -ItemType Directory -Force -Path $DataDir | Out-Null
New-Item -ItemType Directory -Force -Path "$DataDir\\logs" | Out-Null
New-Item -ItemType Directory -Force -Path "$DataDir\\db" | Out-Null

# Install Python dependencies
Write-Step "Installing Python dependencies..."
python -m pip install --quiet --upgrade pip
python -m pip install --quiet -r "$InstallDir\\requirements.txt"

# Create .env file if not exists
$envFile = "$DataDir\\.env"
if (-not (Test-Path $envFile)) {{
    Write-Step "Creating default configuration..."
    @"
SINTRA_DATA_DIR=$DataDir
SINTRA_LOG_LEVEL=INFO
SINTRA_AUTO_UPDATE={("true" if cfg.enable_auto_update else "false")}
OPENAI_API_KEY=
AIRTABLE_API_KEY=
STRIPE_SECRET_KEY=
"@ | Out-File -FilePath $envFile -Encoding UTF8
}}

# Registry entries for Add/Remove Programs
Write-Step "Registering application..."
$regPath = "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}"
New-Item -Path $regPath -Force | Out-Null
Set-ItemProperty -Path $regPath -Name "DisplayName" -Value "{cfg.name}"
Set-ItemProperty -Path $regPath -Name "DisplayVersion" -Value "{cfg.version}"
Set-ItemProperty -Path $regPath -Name "Publisher" -Value "{cfg.author}"
Set-ItemProperty -Path $regPath -Name "InstallLocation" -Value $InstallDir
Set-ItemProperty -Path $regPath -Name "UninstallString" -Value "powershell -File `"$InstallDir\\setup.ps1`" -Uninstall"
Set-ItemProperty -Path $regPath -Name "NoModify" -Value 1
Set-ItemProperty -Path $regPath -Name "NoRepair" -Value 1
{startup_block}
# Desktop shortcut
Write-Step "Creating desktop shortcut..."
$WshShell = New-Object -ComObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("$env:PUBLIC\\Desktop\\{cfg.name}.lnk")
$Shortcut.TargetPath = "$InstallDir\\{cfg.name}.exe"
$Shortcut.WorkingDirectory = $InstallDir
$Shortcut.Description = "{cfg.description}"
$Shortcut.Save()

Write-Host ""
Write-Host "  {cfg.name} v{cfg.version} installed successfully!" -ForegroundColor Green
Write-Host "  Launch from Desktop shortcut or: $InstallDir\\{cfg.name}.exe" -ForegroundColor Cyan
Write-Host ""
"""
        return DeploymentArtifact(
            artifact_id=f"ps_{uuid.uuid4().hex[:6]}",
            artifact_type="powershell_setup",
            filename="setup.ps1",
            content=content,
            description="PowerShell installation script (requires admin)",
        )


class PyInstallerSpecGenerator:
    """Generates the PyInstaller .spec file for building the .exe."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        content = f"""# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for {cfg.name} v{cfg.version}
# Generated by SintraPrime Windows Deployer

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['{cfg.entry_point}'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('assets', 'assets'),
        ('phase16', 'phase16'),
        ('phase17', 'phase17'),
        ('integrations', 'integrations'),
        ('agents', 'agents'),
        ('parl', 'parl'),
        ('channels', 'channels'),
        ('core', 'core'),
    ],
    hiddenimports=[
        'openai',
        'aiohttp',
        'pydantic',
        'sqlalchemy',
        'discord',
        'stripe',
        'requests',
        'numpy',
        'phase16.parl_core',
        'phase16.moe_router',
        'phase16.stripe_billing',
        'phase16.multi_tenant',
        'phase16.contract_redline',
        'phase16.mobile_app',
        'phase16.advanced_analytics',
        'phase17.llm_wiring',
        'integrations.airtable_crm',
        'agents.chat',
        'agents.zero',
        'agents.sigma',
        'agents.nova',
    ],
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['pytest', 'unittest', 'test_*', 'tests'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='{cfg.name}',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='{cfg.icon_path}',
    version='version_info.txt',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='{cfg.name}',
)
"""
        return DeploymentArtifact(
            artifact_id=f"spec_{uuid.uuid4().hex[:6]}",
            artifact_type="pyinstaller_spec",
            filename=f"{cfg.name}.spec",
            content=content,
            description="PyInstaller spec file for building Windows .exe",
        )


class NSISInstallerGenerator:
    """Generates the NSIS installer script (.nsi)."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        content = f"""; NSIS Installer Script for {cfg.name} v{cfg.version}
; Generated by SintraPrime Windows Deployer

!include "MUI2.nsh"
!include "LogicLib.nsh"

; General
Name "{cfg.name}"
OutFile "{cfg.name}_v{cfg.version}_Setup.exe"
InstallDir "{cfg.install_dir}"
InstallDirRegKey HKLM "Software\\{cfg.name}" "Install_Dir"
RequestExecutionLevel admin
SetCompressor /SOLID lzma

; Version info
VIProductVersion "{cfg.version}.0"
VIAddVersionKey "ProductName" "{cfg.name}"
VIAddVersionKey "CompanyName" "{cfg.author}"
VIAddVersionKey "FileDescription" "{cfg.description}"
VIAddVersionKey "FileVersion" "{cfg.version}"
VIAddVersionKey "ProductVersion" "{cfg.version}"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON "{cfg.icon_path}"
!define MUI_UNICON "{cfg.icon_path}"
!define MUI_WELCOMEPAGE_TITLE "Welcome to {cfg.name} v{cfg.version}"
!define MUI_WELCOMEPAGE_TEXT "{cfg.description}$\\r$\\n$\\r$\\nClick Next to continue."
!define MUI_FINISHPAGE_RUN "$INSTDIR\\{cfg.name}.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch {cfg.name} now"

; Pages
!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; Languages
!insertmacro MUI_LANGUAGE "English"

; Installer sections
Section "{cfg.name} (required)" SecMain
  SectionIn RO
  SetOutPath "$INSTDIR"

  ; Copy application files
  File /r "dist\\{cfg.name}\\*.*"

  ; Create data directory
  CreateDirectory "$APPDATA\\{cfg.name}"
  CreateDirectory "$APPDATA\\{cfg.name}\\logs"
  CreateDirectory "$APPDATA\\{cfg.name}\\db"

  ; Write registry keys
  WriteRegStr HKLM "Software\\{cfg.name}" "Install_Dir" "$INSTDIR"
  WriteRegStr HKLM "Software\\{cfg.name}" "Version" "{cfg.version}"

  ; Add/Remove Programs entry
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "DisplayName" "{cfg.name}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "DisplayVersion" "{cfg.version}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "Publisher" "{cfg.author}"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "UninstallString" '"$INSTDIR\\Uninstall.exe"'
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "NoModify" 1
  WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}" "NoRepair" 1

  ; Create shortcuts
  CreateDirectory "$SMPROGRAMS\\{cfg.name}"
  CreateShortcut "$SMPROGRAMS\\{cfg.name}\\{cfg.name}.lnk" "$INSTDIR\\{cfg.name}.exe"
  CreateShortcut "$DESKTOP\\{cfg.name}.lnk" "$INSTDIR\\{cfg.name}.exe"

  ; Write uninstaller
  WriteUninstaller "$INSTDIR\\Uninstall.exe"
SectionEnd

; Uninstaller
Section "Uninstall"
  Delete "$INSTDIR\\Uninstall.exe"
  RMDir /r "$INSTDIR"

  ; Remove shortcuts
  Delete "$SMPROGRAMS\\{cfg.name}\\{cfg.name}.lnk"
  RMDir "$SMPROGRAMS\\{cfg.name}"
  Delete "$DESKTOP\\{cfg.name}.lnk"

  ; Remove registry keys
  DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}"
  DeleteRegKey HKLM "Software\\{cfg.name}"

  MessageBox MB_YESNO "Remove user data ($APPDATA\\{cfg.name})?" IDNO NoRemoveData
    RMDir /r "$APPDATA\\{cfg.name}"
  NoRemoveData:
SectionEnd
"""
        return DeploymentArtifact(
            artifact_id=f"nsis_{uuid.uuid4().hex[:6]}",
            artifact_type="nsis_installer",
            filename=f"{cfg.name}_installer.nsi",
            content=content,
            description="NSIS installer script for building Windows .exe installer",
        )


class AutoUpdaterConfigGenerator:
    """Generates the auto-updater configuration."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        content = f"""{{
  "appName": "{cfg.name}",
  "currentVersion": "{cfg.version}",
  "updateCheckUrl": "https://api.sintra.ai/updates/check",
  "updateDownloadUrl": "https://releases.sintra.ai/windows/",
  "checkIntervalHours": 24,
  "autoDownload": false,
  "autoInstallOnQuit": true,
  "allowPrerelease": false,
  "allowDowngrade": false,
  "channel": "stable",
  "publisherName": "{cfg.author}",
  "icon": "{cfg.icon_path}",
  "releaseNotesUrl": "https://sintra.ai/changelog",
  "installMode": "{"perMachine" if cfg.target == DeploymentTarget.ALL_USERS else "currentUser"}",
  "requestHeaders": {{
    "User-Agent": "{cfg.name}/{cfg.version} (Windows)"
  }}
}}
"""
        return DeploymentArtifact(
            artifact_id=f"upd_{uuid.uuid4().hex[:6]}",
            artifact_type="autoupdater_config",
            filename="updater.json",
            content=content,
            description="Auto-updater configuration (electron-updater compatible)",
        )


class SystemTrayConfigGenerator:
    """Generates the system tray application configuration."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        content = f"""# {cfg.name} System Tray Configuration
# Generated by SintraPrime Windows Deployer

[app]
name = {cfg.name}
version = {cfg.version}
icon = {cfg.icon_path}
tooltip = {cfg.name} — {cfg.description}
start_minimized = true
minimize_to_tray = true
close_to_tray = true

[server]
host = 127.0.0.1
port = 8765
auto_start = true
auto_restart = true
restart_delay_seconds = 3

[notifications]
enable = true
show_on_startup = true
show_on_update = true
show_on_error = true
sound = false

[menu]
# System tray right-click menu items
item_1_label = Open {cfg.name}
item_1_action = open_window
item_2_label = ---
item_3_label = New Chat
item_3_action = new_chat
item_4_label = Run Tests
item_4_action = run_tests
item_5_label = View Logs
item_5_action = open_logs
item_6_label = ---
item_7_label = Settings
item_7_action = open_settings
item_8_label = Check for Updates
item_8_action = check_updates
item_9_label = ---
item_10_label = Quit {cfg.name}
item_10_action = quit

[hotkeys]
toggle_window = Ctrl+Shift+S
new_chat = Ctrl+Shift+N
"""
        return DeploymentArtifact(
            artifact_id=f"tray_{uuid.uuid4().hex[:6]}",
            artifact_type="system_tray_config",
            filename="tray_config.ini",
            content=content,
            description="System tray application configuration",
        )


class RegistryManifestGenerator:
    """Generates the Windows Registry manifest (.reg file)."""

    def generate(self, cfg: AppConfig) -> DeploymentArtifact:
        content = f"""Windows Registry Editor Version 5.00

; {cfg.name} v{cfg.version} Registry Manifest
; Generated by SintraPrime Windows Deployer
; Run as Administrator to apply

; Application registration
[HKEY_LOCAL_MACHINE\\Software\\{cfg.name}]
"InstallDir"="{cfg.install_dir.replace(chr(92), chr(92)+chr(92))}"
"Version"="{cfg.version}"
"DataDir"="%APPDATA%\\{cfg.name}"
"AutoUpdate"=dword:{"00000001" if cfg.enable_auto_update else "00000000"}

; File associations — .sintra files
[HKEY_CLASSES_ROOT\\.sintra]
@="{cfg.name}.Document"
"Content Type"="application/x-sintra"

[HKEY_CLASSES_ROOT\\{cfg.name}.Document]
@="{cfg.name} Document"

[HKEY_CLASSES_ROOT\\{cfg.name}.Document\\DefaultIcon]
@="{cfg.install_dir.replace(chr(92), chr(92)+chr(92))}\\\\{cfg.name}.exe,0"

[HKEY_CLASSES_ROOT\\{cfg.name}.Document\\shell\\open\\command]
@="\\"{cfg.install_dir.replace(chr(92), chr(92)+chr(92))}\\\\{cfg.name}.exe\\" \\"%1\\""

; Add to PATH (optional — comment out if not needed)
[HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment]
; "Path" updated by installer — do not edit manually

; Uninstall entry
[HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{cfg.name}]
"DisplayName"="{cfg.name}"
"DisplayVersion"="{cfg.version}"
"Publisher"="{cfg.author}"
"InstallLocation"="{cfg.install_dir.replace(chr(92), chr(92)+chr(92))}"
"NoModify"=dword:00000001
"NoRepair"=dword:00000001
"""
        return DeploymentArtifact(
            artifact_id=f"reg_{uuid.uuid4().hex[:6]}",
            artifact_type="registry_manifest",
            filename=f"{cfg.name}_registry.reg",
            content=content,
            description="Windows Registry manifest (.reg) for manual application",
        )


# ─────────────────────────────────────────────────────────────────────────────
# Main deployer
# ─────────────────────────────────────────────────────────────────────────────

class WindowsDeployer:
    """Orchestrates generation of all Windows deployment artifacts."""

    def __init__(self, app_config: Optional[AppConfig] = None):
        self.app_config = app_config or AppConfig()
        self._ps_gen = PowerShellSetupGenerator()
        self._spec_gen = PyInstallerSpecGenerator()
        self._nsis_gen = NSISInstallerGenerator()
        self._updater_gen = AutoUpdaterConfigGenerator()
        self._tray_gen = SystemTrayConfigGenerator()
        self._reg_gen = RegistryManifestGenerator()

    def generate_bundle(self) -> DeploymentBundle:
        """Generate the complete deployment bundle."""
        cfg = self.app_config
        bundle = DeploymentBundle(
            bundle_id=f"bundle_{uuid.uuid4().hex[:8]}",
            app_config=cfg,
        )

        bundle.artifacts.append(self._ps_gen.generate(cfg))
        bundle.artifacts.append(self._spec_gen.generate(cfg))
        bundle.artifacts.append(self._nsis_gen.generate(cfg))
        if cfg.enable_auto_update:
            bundle.artifacts.append(self._updater_gen.generate(cfg))
        if cfg.enable_system_tray:
            bundle.artifacts.append(self._tray_gen.generate(cfg))
        bundle.artifacts.append(self._reg_gen.generate(cfg))

        return bundle

    def generate_artifact(self, artifact_type: str) -> Optional[DeploymentArtifact]:
        """Generate a single artifact by type."""
        cfg = self.app_config
        generators = {
            "powershell_setup": self._ps_gen,
            "pyinstaller_spec": self._spec_gen,
            "nsis_installer": self._nsis_gen,
            "autoupdater_config": self._updater_gen,
            "system_tray_config": self._tray_gen,
            "registry_manifest": self._reg_gen,
        }
        gen = generators.get(artifact_type)
        return gen.generate(cfg) if gen else None

    def validate_bundle(self, bundle: DeploymentBundle) -> Dict[str, Any]:
        """Validate that all required artifacts are present and non-empty."""
        required = ["powershell_setup", "pyinstaller_spec", "nsis_installer", "registry_manifest"]
        missing = [r for r in required if r not in bundle.artifact_types()]
        empty = [a.artifact_type for a in bundle.artifacts if not a.content.strip()]

        return {
            "valid": len(missing) == 0 and len(empty) == 0,
            "missing_artifacts": missing,
            "empty_artifacts": empty,
            "total_artifacts": len(bundle.artifacts),
            "total_size_bytes": bundle.total_size_bytes(),
        }
