"""
Phase 15B — Windows Desktop Executable Builder
Generates a 1-click PyInstaller spec, build script, NSIS installer script,
and Windows taskbar tray icon integration for SintraPrime.

Usage:
    builder = ExeBuilder(config)
    builder.generate_all()   # writes all files to output_dir
    builder.build()          # runs PyInstaller (Windows only)
"""
from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class ExeConfig:
    app_name: str = "SintraPrime"
    app_version: str = "1.0.0"
    app_description: str = "AI-Powered Legal Assistant"
    company_name: str = "SintraPrime Inc."
    author: str = "SintraPrime Team"
    main_script: str = "main.py"
    icon_path: str = "assets/sintra_icon.ico"
    output_dir: str = "dist"
    build_dir: str = "build"
    one_file: bool = True
    windowed: bool = True  # No console window
    uac_admin: bool = False
    add_data: List[str] = field(default_factory=list)
    hidden_imports: List[str] = field(default_factory=list)
    exclude_modules: List[str] = field(default_factory=list)
    runtime_hooks: List[str] = field(default_factory=list)
    nsis_output_dir: str = "installer"
    tray_enabled: bool = True
    auto_start: bool = False  # Add to Windows startup
    port: int = 8765  # Local API server port

    def to_dict(self) -> Dict[str, Any]:
        return {
            "app_name": self.app_name,
            "app_version": self.app_version,
            "app_description": self.app_description,
            "company_name": self.company_name,
            "author": self.author,
            "main_script": self.main_script,
            "icon_path": self.icon_path,
            "output_dir": self.output_dir,
            "one_file": self.one_file,
            "windowed": self.windowed,
            "tray_enabled": self.tray_enabled,
            "auto_start": self.auto_start,
            "port": self.port,
        }


# ---------------------------------------------------------------------------
# PyInstaller spec generator
# ---------------------------------------------------------------------------

class SpecGenerator:
    """Generates a .spec file for PyInstaller."""

    def __init__(self, config: ExeConfig):
        self.config = config

    def generate(self) -> str:
        c = self.config
        add_data_str = ", ".join(
            f"('{src}', '{dst}')" for src, dst in
            [d.split(";") for d in c.add_data] if ";" in d
        ) if c.add_data else ""

        hidden_imports_str = ", ".join(f"'{m}'" for m in c.hidden_imports)
        exclude_str = ", ".join(f"'{m}'" for m in c.exclude_modules)
        runtime_hooks_str = ", ".join(f"'{h}'" for h in c.runtime_hooks)

        mode = "EXE" if c.one_file else "COLLECT"
        console_flag = "False" if c.windowed else "True"
        uac_flag = "True" if c.uac_admin else "False"

        spec = textwrap.dedent(f"""\
            # -*- mode: python ; coding: utf-8 -*-
            # Auto-generated by SintraPrime ExeBuilder v{c.app_version}

            block_cipher = None

            a = Analysis(
                ['{c.main_script}'],
                pathex=[],
                binaries=[],
                datas=[{add_data_str}],
                hiddenimports=[{hidden_imports_str}],
                hookspath=[],
                hooksconfig={{}},
                runtime_hooks=[{runtime_hooks_str}],
                excludes=[{exclude_str}],
                win_no_prefer_redirects=False,
                win_private_assemblies=False,
                cipher=block_cipher,
                noarchive=False,
            )

            pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

            exe = EXE(
                pyz,
                a.scripts,
                {'a.binaries,' if c.one_file else '[],'} 
                {'a.zipfiles,' if c.one_file else '[],'} 
                {'a.datas,' if c.one_file else '[],'} 
                [],
                name='{c.app_name}',
                debug=False,
                bootloader_ignore_signals=False,
                strip=False,
                upx=True,
                upx_exclude=[],
                runtime_tmpdir=None,
                console={console_flag},
                disable_windowed_traceback=False,
                argv_emulation=False,
                target_arch=None,
                codesign_identity=None,
                entitlements_file=None,
                icon='{c.icon_path}',
                uac_admin={uac_flag},
                version='version_info.txt',
            )
        """)

        if not c.one_file:
            spec += textwrap.dedent(f"""
            coll = COLLECT(
                exe,
                a.binaries,
                a.zipfiles,
                a.datas,
                strip=False,
                upx=True,
                upx_exclude=[],
                name='{c.app_name}',
            )
            """)

        return spec

    def generate_version_info(self) -> str:
        c = self.config
        major, minor, patch = (c.app_version.split(".") + ["0", "0", "0"])[:3]
        return textwrap.dedent(f"""\
            VSVersionInfo(
              ffi=FixedFileInfo(
                filevers=({major}, {minor}, {patch}, 0),
                prodvers=({major}, {minor}, {patch}, 0),
                mask=0x3f,
                flags=0x0,
                OS=0x40004,
                fileType=0x1,
                subtype=0x0,
                date=(0, 0)
              ),
              kids=[
                StringFileInfo([
                  StringTable(
                    u'040904B0',
                    [StringStruct(u'CompanyName', u'{c.company_name}'),
                     StringStruct(u'FileDescription', u'{c.app_description}'),
                     StringStruct(u'FileVersion', u'{c.app_version}'),
                     StringStruct(u'InternalName', u'{c.app_name}'),
                     StringStruct(u'LegalCopyright', u'Copyright 2025 {c.company_name}'),
                     StringStruct(u'OriginalFilename', u'{c.app_name}.exe'),
                     StringStruct(u'ProductName', u'{c.app_name}'),
                     StringStruct(u'ProductVersion', u'{c.app_version}')])
                ]),
                VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
              ]
            )
        """)


# ---------------------------------------------------------------------------
# NSIS installer script generator
# ---------------------------------------------------------------------------

class NSISGenerator:
    """Generates a NSIS installer script (.nsi) for Windows."""

    def __init__(self, config: ExeConfig):
        self.config = config

    def generate(self) -> str:
        c = self.config
        auto_start_section = ""
        if c.auto_start:
            auto_start_section = textwrap.dedent(f"""
            Section "Auto-start on login"
              WriteRegStr HKCU "Software\\Microsoft\\Windows\\CurrentVersion\\Run" \\
                "{c.app_name}" "$INSTDIR\\{c.app_name}.exe"
            SectionEnd
            """)

        return textwrap.dedent(f"""\
            ; NSIS Installer Script for {c.app_name}
            ; Auto-generated by SintraPrime ExeBuilder v{c.app_version}

            !include "MUI2.nsh"
            !include "FileFunc.nsh"

            Name "{c.app_name}"
            OutFile "{c.nsis_output_dir}\\{c.app_name}_Setup_v{c.app_version}.exe"
            InstallDir "$PROGRAMFILES64\\{c.company_name}\\{c.app_name}"
            InstallDirRegKey HKLM "Software\\{c.company_name}\\{c.app_name}" "InstallDir"
            RequestExecutionLevel admin

            ; MUI Settings
            !define MUI_ABORTWARNING
            !define MUI_ICON "{c.icon_path}"
            !define MUI_UNICON "{c.icon_path}"
            !define MUI_WELCOMEPAGE_TITLE "Welcome to {c.app_name} Setup"
            !define MUI_WELCOMEPAGE_TEXT "This wizard will install {c.app_name} v{c.app_version} on your computer.$\\n$\\n{c.app_description}"

            ; Pages
            !insertmacro MUI_PAGE_WELCOME
            !insertmacro MUI_PAGE_LICENSE "LICENSE.txt"
            !insertmacro MUI_PAGE_DIRECTORY
            !insertmacro MUI_PAGE_INSTFILES
            !insertmacro MUI_PAGE_FINISH

            !insertmacro MUI_UNPAGE_CONFIRM
            !insertmacro MUI_UNPAGE_INSTFILES

            !insertmacro MUI_LANGUAGE "English"

            ; Version Information
            VIProductVersion "{c.app_version}.0"
            VIAddVersionKey "ProductName" "{c.app_name}"
            VIAddVersionKey "CompanyName" "{c.company_name}"
            VIAddVersionKey "FileDescription" "{c.app_description} Installer"
            VIAddVersionKey "FileVersion" "{c.app_version}"

            Section "Main Application" SEC01
              SetOutPath "$INSTDIR"
              File "{c.output_dir}\\{c.app_name}.exe"
              File /r "assets"

              ; Create shortcuts
              CreateDirectory "$SMPROGRAMS\\{c.company_name}"
              CreateShortCut "$SMPROGRAMS\\{c.company_name}\\{c.app_name}.lnk" "$INSTDIR\\{c.app_name}.exe"
              CreateShortCut "$DESKTOP\\{c.app_name}.lnk" "$INSTDIR\\{c.app_name}.exe"

              ; Registry entries
              WriteRegStr HKLM "Software\\{c.company_name}\\{c.app_name}" "InstallDir" "$INSTDIR"
              WriteRegStr HKLM "Software\\{c.company_name}\\{c.app_name}" "Version" "{c.app_version}"

              ; Add/Remove Programs entry
              WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "DisplayName" "{c.app_name}"
              WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "UninstallString" "$INSTDIR\\Uninstall.exe"
              WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "DisplayVersion" "{c.app_version}"
              WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "Publisher" "{c.company_name}"
              WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "NoModify" 1
              WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}" \\
                "NoRepair" 1

              WriteUninstaller "$INSTDIR\\Uninstall.exe"
            SectionEnd
            {auto_start_section}
            Section "Uninstall"
              Delete "$INSTDIR\\{c.app_name}.exe"
              Delete "$INSTDIR\\Uninstall.exe"
              RMDir /r "$INSTDIR\\assets"
              RMDir "$INSTDIR"
              Delete "$SMPROGRAMS\\{c.company_name}\\{c.app_name}.lnk"
              RMDir "$SMPROGRAMS\\{c.company_name}"
              Delete "$DESKTOP\\{c.app_name}.lnk"
              DeleteRegKey HKLM "Software\\{c.company_name}\\{c.app_name}"
              DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{c.app_name}"
            SectionEnd
        """)


# ---------------------------------------------------------------------------
# Tray icon integration (pystray-based)
# ---------------------------------------------------------------------------

class TrayIconGenerator:
    """Generates the Windows system tray icon integration script."""

    def __init__(self, config: ExeConfig):
        self.config = config

    def generate(self) -> str:
        c = self.config
        return textwrap.dedent(f"""\
            \"\"\"
            SintraPrime Windows Taskbar Tray Icon
            Auto-generated by ExeBuilder v{c.app_version}
            \"\"\"
            import threading
            import webbrowser
            import sys
            import os

            try:
                import pystray
                from PIL import Image
                TRAY_AVAILABLE = True
            except ImportError:
                TRAY_AVAILABLE = False

            SINTRA_URL = "http://localhost:{c.port}"
            ICON_PATH = os.path.join(os.path.dirname(__file__), "assets", "sintra_icon.ico")


            def _open_dashboard(_icon=None, _item=None):
                webbrowser.open(SINTRA_URL)


            def _open_settings(_icon=None, _item=None):
                webbrowser.open(f"{{SINTRA_URL}}/settings")


            def _quit_app(icon, _item=None):
                icon.stop()
                sys.exit(0)


            def _load_icon():
                try:
                    return Image.open(ICON_PATH)
                except Exception:
                    # Fallback: create a simple 64x64 blue square
                    img = Image.new("RGB", (64, 64), color=(30, 100, 200))
                    return img


            def run_tray():
                if not TRAY_AVAILABLE:
                    return
                icon = pystray.Icon(
                    name="{c.app_name}",
                    icon=_load_icon(),
                    title="{c.app_name} — {c.app_description}",
                    menu=pystray.Menu(
                        pystray.MenuItem("Open Dashboard", _open_dashboard, default=True),
                        pystray.MenuItem("Settings", _open_settings),
                        pystray.Menu.SEPARATOR,
                        pystray.MenuItem("Quit {c.app_name}", _quit_app),
                    ),
                )
                icon.run()


            def start_tray_in_background():
                t = threading.Thread(target=run_tray, daemon=True)
                t.start()
                return t


            if __name__ == "__main__":
                run_tray()
        """)


# ---------------------------------------------------------------------------
# Build script generator
# ---------------------------------------------------------------------------

class BuildScriptGenerator:
    """Generates the build.bat / build.sh script."""

    def __init__(self, config: ExeConfig):
        self.config = config

    def generate_bat(self) -> str:
        c = self.config
        return textwrap.dedent(f"""\
            @echo off
            REM SintraPrime Windows Build Script v{c.app_version}
            REM Auto-generated by ExeBuilder

            echo Building {c.app_name} v{c.app_version}...

            REM Install dependencies
            pip install pyinstaller pystray pillow --quiet

            REM Clean previous builds
            if exist "{c.build_dir}" rmdir /s /q "{c.build_dir}"
            if exist "{c.output_dir}\\{c.app_name}.exe" del /f "{c.output_dir}\\{c.app_name}.exe"

            REM Build executable
            pyinstaller {c.app_name}.spec --clean --noconfirm

            if %ERRORLEVEL% neq 0 (
                echo BUILD FAILED
                exit /b 1
            )

            echo Build successful: {c.output_dir}\\{c.app_name}.exe

            REM Build installer (requires NSIS)
            where makensis >nul 2>&1
            if %ERRORLEVEL% equ 0 (
                echo Building installer...
                if not exist "{c.nsis_output_dir}" mkdir "{c.nsis_output_dir}"
                makensis {c.app_name}_installer.nsi
                echo Installer: {c.nsis_output_dir}\\{c.app_name}_Setup_v{c.app_version}.exe
            ) else (
                echo NSIS not found — skipping installer build
            )

            echo Done!
        """)

    def generate_sh(self) -> str:
        c = self.config
        return textwrap.dedent(f"""\
            #!/bin/bash
            # SintraPrime Build Script (Linux/macOS CI) v{c.app_version}
            set -e

            echo "Building {c.app_name} v{c.app_version}..."

            pip install pyinstaller pystray pillow --quiet

            rm -rf "{c.build_dir}" "{c.output_dir}/{c.app_name}"

            pyinstaller {c.app_name}.spec --clean --noconfirm

            echo "Build complete: {c.output_dir}/{c.app_name}"
        """)


# ---------------------------------------------------------------------------
# Main ExeBuilder orchestrator
# ---------------------------------------------------------------------------

class ExeBuilder:
    """
    Orchestrates generation of all Windows deployment artifacts:
    - PyInstaller .spec file
    - version_info.txt
    - NSIS installer script
    - Tray icon integration script
    - Build scripts (bat + sh)
    - build_config.json
    """

    def __init__(self, config: Optional[ExeConfig] = None, output_dir: Optional[str] = None):
        self.config = config or ExeConfig()
        if output_dir:
            self.config.output_dir = output_dir
        self._spec_gen = SpecGenerator(self.config)
        self._nsis_gen = NSISGenerator(self.config)
        self._tray_gen = TrayIconGenerator(self.config)
        self._build_gen = BuildScriptGenerator(self.config)
        self._generated_files: List[str] = []

    def generate_all(self, base_dir: str = ".") -> Dict[str, str]:
        """
        Generate all deployment artifacts into base_dir.
        Returns a dict of {filename: content}.
        """
        base = Path(base_dir)
        base.mkdir(parents=True, exist_ok=True)

        artifacts: Dict[str, str] = {
            f"{self.config.app_name}.spec": self._spec_gen.generate(),
            "version_info.txt": self._spec_gen.generate_version_info(),
            f"{self.config.app_name}_installer.nsi": self._nsis_gen.generate(),
            "tray_icon.py": self._tray_gen.generate(),
            "build.bat": self._build_gen.generate_bat(),
            "build.sh": self._build_gen.generate_sh(),
            "build_config.json": json.dumps(self.config.to_dict(), indent=2),
        }

        for filename, content in artifacts.items():
            path = base / filename
            path.write_text(content, encoding="utf-8")
            self._generated_files.append(str(path))

        return artifacts

    def get_generated_files(self) -> List[str]:
        return list(self._generated_files)

    def validate_config(self) -> List[str]:
        """Returns list of validation warnings."""
        warnings: List[str] = []
        if not self.config.main_script.endswith(".py"):
            warnings.append("main_script should end with .py")
        if not self.config.icon_path.endswith((".ico", ".png")):
            warnings.append("icon_path should be .ico or .png")
        if self.config.port < 1024 or self.config.port > 65535:
            warnings.append(f"port {self.config.port} is outside recommended range 1024-65535")
        if self.config.app_version.count(".") < 2:
            warnings.append("app_version should be in X.Y.Z format")
        return warnings

    def build(self, cwd: Optional[str] = None) -> subprocess.CompletedProcess:
        """
        Runs PyInstaller with the generated spec file.
        Only works on the host OS where PyInstaller is installed.
        """
        spec_file = f"{self.config.app_name}.spec"
        cmd = [sys.executable, "-m", "PyInstaller", spec_file, "--clean", "--noconfirm"]
        return subprocess.run(
            cmd,
            cwd=cwd or ".",
            capture_output=True,
            text=True,
        )

    @classmethod
    def from_json(cls, json_path: str) -> "ExeBuilder":
        with open(json_path, encoding="utf-8") as f:
            data = json.load(f)
        config = ExeConfig(**{k: v for k, v in data.items() if hasattr(ExeConfig, k)})
        return cls(config)
