"""Validated legal authority vocabulary and hierarchy."""

SOURCE_CLASSIFICATIONS = {
    "PRIMARY_LEGAL_AUTHORITY",
    "OFFICIAL_FORM",
    "OFFICIAL_GUIDANCE",
    "COURT_DECISION",
    "SECONDARY_LEGAL_SOURCE",
    "PROFESSIONAL_STANDARD",
    "CLIENT_DOCUMENT",
    "EDUCATIONAL_MATERIAL",
    "PRIVATE_TEMPLATE",
    "UNVERIFIED_PRIVATE_LAW_CLAIM",
    "UNKNOWN",
}

VERIFICATION_STATES = {
    "UNVERIFIED",
    "SECONDARY_SOURCE_ONLY",
    "PRIMARY_SOURCE_LOCATED",
    "PRIMARY_SOURCE_VERIFIED",
    "CONFLICTING_AUTHORITY",
    "SUPERSEDED",
    "HUMAN_REVIEW_REQUIRED",
    "HUMAN_REVIEWED",
    "PRODUCTION_ELIGIBLE",
}

RULE_STATUSES = {
    "DRAFT",
    "ACTIVE",
    "HISTORICAL",
    "CONFLICTING_AUTHORITY",
    "SUPERSEDED",
    "HUMAN_REVIEW_REQUIRED",
    "QUARANTINED",
}

RULE_CATEGORIES = {
    "STATE_RULE",
    "FEDERAL_OVERLAY",
    "BANKRUPTCY_ONLY_RULE",
    "PROCEDURAL_RULE",
    "EXEMPTION_RULE",
}

REVIEWER_ROLES = {
    "LEGAL_RESEARCHER",
    "LICENSED_ATTORNEY",
    "CPA",
    "SECURITY_REVIEWER",
    "PRIVACY_REVIEWER",
    "PLATFORM_ADMIN",
}

REVIEW_STATES = {
    "NOT_SUBMITTED",
    "SUBMITTED",
    "IN_REVIEW",
    "CHANGES_REQUESTED",
    "APPROVED_WITH_CONDITIONS",
    "APPROVED",
    "REJECTED",
    "WITHDRAWN",
    "SUPERSEDED",
}

CHALLENGE_STATES = {
    "OPEN",
    "UNDER_REVIEW",
    "SUPPORTED",
    "PARTIALLY_SUPPORTED",
    "REJECTED",
    "CORRECTION_REQUIRED",
    "RESOLVED",
}

CHALLENGE_TYPES = {
    "CITATION_ACCURACY",
    "AUTHORITY_CLASSIFICATION",
    "RULE_STATEMENT",
    "EFFECTIVE_DATE",
    "SUPERSESSION",
    "AUTHORITY_HIERARCHY",
    "ENCODED_LOGIC",
    "EXCEPTIONS",
    "JURISDICTION_SCOPE",
    "CONFIDENCE",
    "PRODUCTION_ELIGIBILITY",
}

CREDENTIAL_VERIFICATION_STATES = {
    "NOT_VERIFIED",
    "SELF_DECLARED",
    "VERIFIED_EXTERNALLY",
    "VERIFICATION_UNAVAILABLE",
}

SOURCE_AVAILABILITY_STATES = {
    "AVAILABLE",
    "UNAVAILABLE",
    "LOCATOR_ONLY",
    "BROKEN_LINK",
    "UNKNOWN",
}

MANUAL_REVIEW_STATES = {
    "NOT_REQUIRED",
    "QUEUED",
    "IN_REVIEW",
    "REVIEWED",
    "INVALIDATED_PENDING_REVIEW",
}

AUDIT_EVENT_TYPES = {
    "REVIEW_SUBMITTED",
    "REVIEW_RECORDED",
    "CHALLENGE_SUBMITTED",
    "CHALLENGE_RESOLVED",
    "SOURCE_REFRESHED",
    "PRODUCTION_GATE_EVALUATED",
}

AUTHORITY_HIERARCHY = {
    "US_CONSTITUTION": 1000,
    "FEDERAL_STATUTE": 950,
    "BINDING_FEDERAL_APPELLATE_DECISION": 900,
    "NEW_JERSEY_CONSTITUTION": 880,
    "NEW_JERSEY_STATUTE": 850,
    "NEW_JERSEY_SUPREME_COURT_DECISION": 820,
    "NEW_JERSEY_APPELLATE_DIVISION_DECISION": 790,
    "NEW_JERSEY_REGULATION": 760,
    "NEW_JERSEY_COURT_RULE": 730,
    "OFFICIAL_AGENCY_GUIDANCE": 700,
    "PERSUASIVE_FEDERAL_DECISION": 650,
    "PERSUASIVE_OUT_OF_STATE_DECISION": 600,
    "RESTATEMENT_OR_UNIFORM_LAW_COMMENTARY": 550,
    "TREATISE_OR_LAW_REVIEW_MATERIAL": 500,
    "GENERAL_SECONDARY_SOURCE": 450,
    "PRIVATE_EDUCATIONAL_MATERIAL": 300,
    "UNSUPPORTED_PRIVATE_CLAIM": 0,
}

SUPPORTED_JURISDICTIONS = {"NJ", "FED"}
