import { useEffect, useState } from 'react';
import { AlertTriangle, GitCompareArrows, Loader2, Scale } from 'lucide-react';
import Badge from '../components/ui/Badge';
import Card from '../components/ui/Card';

const WARNING = 'Applicable law depends on governing-law rules, trust situs, administration, party contacts, asset location, public policy, and other facts. A favorable rule in another jurisdiction may not govern the matter.';

type Row = { jurisdiction: string; rule?: { id: string; rule_statement: string; topic: string; effective_from?: string | null } | null; confidence: number; review_status: string; material_differences: string[]; missing_data: string[]; source_limitations: string[] };
const topics = ['spendthrift', 'self-settled asset protection', 'continuation window', 'UCC filing office', 'resident trust', 'wage garnishment', 'tenancy by entirety', 'decanting', 'directed trust', 'trust protector'];
const domains = ['trust_law', 'creditor_protection', 'ucc_article9', 'trust_tax'];

export default function NortheastComparison() {
  const [topic, setTopic] = useState('spendthrift');
  const [domain, setDomain] = useState('trust_law');
  const [rows, setRows] = useState<Row[]>([]);
  const [loading, setLoading] = useState(false);
  useEffect(() => { let mounted = true; setLoading(true); fetch(`/legal-rules/compare?jurisdictions=NJ,NY,PA,DE,CT&domain=${encodeURIComponent(domain)}&topic=${encodeURIComponent(topic)}`).then((r) => r.ok ? r.json() : null).then((payload) => { if (!mounted) return; setRows(payload?.rows || []); }).catch(() => { if (mounted) setRows([]); }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [domain, topic]);
  return <section className="space-y-6" aria-labelledby="northeast-title"><div className="rounded-lg border border-gold/25 bg-slate-950/80 p-5 md:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-gold">Regional Comparison</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 id="northeast-title" className="text-3xl font-black text-white md:text-4xl">Northeast Trust Comparison</h1><Badge variant="amber">Human review required</Badge></div><p className="mt-3 max-w-4xl text-sm leading-6 text-slate-400">{WARNING}</p></div><Card padding="lg" gold className="rounded-lg"><div className="grid gap-3 md:grid-cols-2"><label><span className="mb-1 block text-xs uppercase tracking-wider text-slate-500">Domain</span><select className="input-dark" value={domain} onChange={(e) => setDomain(e.target.value)}>{domains.map((item) => <option key={item} value={item}>{item.replace(/_/g, ' ')}</option>)}</select></label><label><span className="mb-1 block text-xs uppercase tracking-wider text-slate-500">Topic</span><select className="input-dark" value={topic} onChange={(e) => setTopic(e.target.value)}>{topics.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div></Card>{loading && <p className="flex items-center gap-2 text-sm text-slate-400"><Loader2 className="h-4 w-4 animate-spin" /> Loading comparison...</p>}<div className="grid gap-4 lg:grid-cols-3">{rows.map((row) => <Card key={row.jurisdiction} padding="lg" className="rounded-lg"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-xl font-bold text-white"><Scale className="h-5 w-5 text-gold" /> {row.jurisdiction}</h2><Badge variant="amber">{row.review_status.replace(/_/g, ' ')}</Badge></div>{row.rule ? <><p className="mt-3 text-xs font-mono text-slate-500">{row.rule.id}</p><p className="mt-3 text-sm leading-6 text-slate-300">{row.rule.rule_statement}</p><p className="mt-3 text-xs text-slate-500">Effective: {row.rule.effective_from || 'review required'} | Confidence: {Math.round(row.confidence * 100)}%</p></> : <p className="mt-4 rounded-lg border border-dashed border-slate-700 p-4 text-sm text-slate-500">No encoded matching rule.</p>}<List title="Material differences" items={row.material_differences} /><List title="Missing data" items={row.missing_data} /><List title="Limitations" items={row.source_limitations} /></Card>)}</div><Card padding="md" className="rounded-lg border-amber-500/30"><p className="flex items-start gap-2 text-sm leading-6 text-amber-100"><AlertTriangle className="mt-1 h-4 w-4 shrink-0" /> The comparison does not rank states as better or safer. It only shows encoded differences, missing data, review state, and limitations.</p></Card></section>;
}
function List({ title, items }: { title: string; items: string[] }) { return <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{title}</p><ul className="mt-2 space-y-1 text-sm text-slate-300">{(items.length ? items : ['None reported.']).slice(0, 3).map((item) => <li key={item}>- {item}</li>)}</ul></div>; }
