"""I2 transition-policy outcomes and fail-closed reason codes."""

from __future__ import annotations

from enum import Enum


class PolicyOutcome(str, Enum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    INCOMPLETE = "INCOMPLETE"


class PolicyReason(str, Enum):
    ALLOWED = "ALLOWED"
    FAILURE_EDGE_ALLOWED = "FAILURE_EDGE_ALLOWED"
    KILL_SWITCH_CANCELLATION = "KILL_SWITCH_CANCELLATION"
    CANCELLATION_REQUESTED = "CANCELLATION_REQUESTED"

    INVALID_INPUT = "INVALID_INPUT"
    AGGREGATE_INTEGRITY_FAILURE = "AGGREGATE_INTEGRITY_FAILURE"
    TERMINAL_STATE_PROHIBITION = "TERMINAL_STATE_PROHIBITION"
    BINDING_FAILURE = "BINDING_FAILURE"
    PREDICATE_NOT_YET_VALID = "PREDICATE_NOT_YET_VALID"
    PREDICATE_EXPIRED = "PREDICATE_EXPIRED"
    INVALID_VALIDITY_WINDOW = "INVALID_VALIDITY_WINDOW"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    KILL_SWITCH_REQUIRES_CANCELLATION = "KILL_SWITCH_REQUIRES_CANCELLATION"
    CANCELLATION_REQUIRES_CANCELLED_EDGE = "CANCELLATION_REQUIRES_CANCELLED_EDGE"
    CANCELLATION_NOT_REQUESTED = "CANCELLATION_NOT_REQUESTED"
    INVALID_GRAPH_EDGE = "INVALID_GRAPH_EDGE"
    CONFLICTING_FAILURE_EVIDENCE = "CONFLICTING_FAILURE_EVIDENCE"
    FAILURE_INDICATOR_BLOCKS_PROGRESS = "FAILURE_INDICATOR_BLOCKS_PROGRESS"
    FAILURE_EDGE_MISMATCH = "FAILURE_EDGE_MISMATCH"
    REQUIRED_PREDICATE_FALSE = "REQUIRED_PREDICATE_FALSE"
    REQUIRED_PREDICATE_UNKNOWN = "REQUIRED_PREDICATE_UNKNOWN"


__all__ = ["PolicyOutcome", "PolicyReason"]
