"""
Document Renderer — Professional multi-format document generation.
Renders documents at the quality level of a top law firm or Big 4 accounting firm.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, List, Optional, Any


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

@dataclass
class DocumentStyle:
    """Visual and formatting style for a document."""
    theme: str                          # legal | financial | corporate | modern | government
    font_family: str
    primary_color: str                  # hex color
    accent_color: str                   # hex color
    logo_text: str
    footer_text: str
    watermark: Optional[str] = None
    page_width: int = 80               # characters for plain-text rendering
    indent_size: int = 4


@dataclass
class RenderedDocument:
    """A fully rendered document in multiple formats."""
    title: str
    content_markdown: str
    content_html: str
    content_text: str
    style: DocumentStyle
    metadata: Dict[str, Any] = field(default_factory=dict)
    page_count: int = 1


@dataclass
class DocumentPackage:
    """A collection of related documents with cover page and TOC."""
    cover_page: str
    table_of_contents: str
    sections: List[RenderedDocument] = field(default_factory=list)
    unified_style: Optional[DocumentStyle] = None

    @property
    def full_text(self) -> str:
        parts = [self.cover_page, self.table_of_contents]
        for i, doc in enumerate(self.sections, 1):
            parts.append(f"\n{'='*80}\n  TAB {i}: {doc.title.upper()}\n{'='*80}\n")
            parts.append(doc.content_text)
        return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Pre-built Style Presets
# ---------------------------------------------------------------------------

LEGAL_TRADITIONAL = DocumentStyle(
    theme="legal",
    font_family="Times New Roman",
    primary_color="#0A1628",       # Dark navy
    accent_color="#B8860B",        # Dark gold
    logo_text="⚖  LEGAL COUNSEL",
    footer_text="CONFIDENTIAL — ATTORNEY-CLIENT PRIVILEGED",
    watermark="DRAFT",
)

FINANCIAL_PROFESSIONAL = DocumentStyle(
    theme="financial",
    font_family="Calibri",
    primary_color="#191970",       # Midnight blue
    accent_color="#C0C0C0",        # Silver
    logo_text="💼 FINANCIAL ADVISORY",
    footer_text="FOR AUTHORIZED RECIPIENTS ONLY — NOT FOR PUBLIC DISTRIBUTION",
    watermark=None,
)

CORPORATE_MODERN = DocumentStyle(
    theme="corporate",
    font_family="Helvetica Neue",
    primary_color="#2D2D2D",       # Dark gray
    accent_color="#0066FF",        # Electric blue
    logo_text="◆ CORPORATE COUNSEL",
    footer_text="PROPRIETARY AND CONFIDENTIAL",
    watermark=None,
)

GOVERNMENT_OFFICIAL = DocumentStyle(
    theme="government",
    font_family="Arial",
    primary_color="#000000",
    accent_color="#555555",
    logo_text="★ OFFICIAL GOVERNMENT DOCUMENT",
    footer_text="OFFICIAL USE ONLY",
    watermark="OFFICIAL",
)

SINTRAPRIME_SIGNATURE = DocumentStyle(
    theme="modern",
    font_family="Inter",
    primary_color="#2E0854",       # Deep purple
    accent_color="#FFD700",        # Gold
    logo_text="⚡ SINTRAPRIME-UNIFIED",
    footer_text="Generated by SintraPrime-Unified · The Sovereign AI · Confidential",
    watermark=None,
)


# ---------------------------------------------------------------------------
# Helper Utilities
# ---------------------------------------------------------------------------

class _Formatter:
    """Internal helper for text formatting."""

    @staticmethod
    def horizontal_rule(width: int = 80, char: str = "═") -> str:
        return char * width

    @staticmethod
    def center(text: str, width: int = 80, fill: str = " ") -> str:
        return text.center(width, fill)

    @staticmethod
    def box(lines: List[str], width: int = 80) -> str:
        inner_w = width - 4
        result = ["╔" + "═" * (width - 2) + "╗"]
        for line in lines:
            padded = line[:inner_w].ljust(inner_w)
            result.append("║  " + padded + "  ║")
        result.append("╚" + "═" * (width - 2) + "╝")
        return "\n".join(result)

    @staticmethod
    def section_header(number: str, title: str, width: int = 80) -> str:
        label = f"{number}. {title.upper()}"
        return f"\n{label}\n{'─' * min(len(label) + 2, width)}\n"

    @staticmethod
    def wrap(text: str, width: int = 76, indent: str = "") -> str:
        return textwrap.fill(text, width=width, initial_indent=indent,
                             subsequent_indent=indent)

    @staticmethod
    def format_currency(amount) -> str:
        try:
            return f"${float(amount):>14,.2f}"
        except (TypeError, ValueError):
            return f"{'[AMOUNT]':>15}"

    @staticmethod
    def format_date(dt=None) -> str:
        if dt is None:
            dt = datetime.now()
        return dt.strftime("%B %d, %Y")

    @staticmethod
    def page_break() -> str:
        return "\n\f\n"  # Form-feed character

    @staticmethod
    def numbered_list(items: List[str], start: int = 1) -> str:
        lines = []
        for i, item in enumerate(items, start):
            lines.append(f"  {i:>2}. {item}")
        return "\n".join(lines)

    @staticmethod
    def alpha_list(items: List[str]) -> str:
        alpha = "abcdefghijklmnopqrstuvwxyz"
        lines = []
        for i, item in enumerate(items):
            lines.append(f"      ({alpha[i]}) {item}")
        return "\n".join(lines)

    @staticmethod
    def roman_section(number: int, title: str) -> str:
        numerals = ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
                    "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX"]
        n = numerals[number - 1] if number <= len(numerals) else str(number)
        return f"\n{n}. {title.upper()}"

    @staticmethod
    def text_to_html(text: str, title: str, style: DocumentStyle) -> str:
        escaped = (text
                   .replace("&", "&amp;")
                   .replace("<", "&lt;")
                   .replace(">", "&gt;"))
        html_body = escaped.replace("\n", "<br>\n")
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{title}</title>
  <style>
    body {{
      font-family: {style.font_family}, serif;
      color: {style.primary_color};
      max-width: 900px;
      margin: 40px auto;
      padding: 40px;
      line-height: 1.6;
    }}
    h1, h2, h3 {{ color: {style.primary_color}; border-bottom: 2px solid {style.accent_color}; }}
    .footer {{ color: #888; font-size: 0.85em; border-top: 1px solid {style.accent_color}; margin-top: 40px; padding-top: 10px; }}
    pre {{ font-family: monospace; white-space: pre-wrap; }}
  </style>
</head>
<body>
  <pre>{html_body}</pre>
  <div class="footer">{style.footer_text}</div>
</body>
</html>"""

    @staticmethod
    def text_to_markdown(text: str, title: str) -> str:
        return f"# {title}\n\n```\n{text}\n```\n"


_fmt = _Formatter()


# ---------------------------------------------------------------------------
# DocumentRenderer
# ---------------------------------------------------------------------------

class DocumentRenderer:
    """
    Renders professional documents in multiple formats.
    All output meets the quality standards of a top law firm or Big 4 firm.
    """

    DEFAULT_STYLE = SINTRAPRIME_SIGNATURE

    def __init__(self, default_style: Optional[DocumentStyle] = None):
        self.default_style = default_style or self.DEFAULT_STYLE

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def render_legal_document(
        self,
        doc: Dict[str, Any],
        style: Optional[DocumentStyle] = None,
    ) -> RenderedDocument:
        """Render a professional legal document."""
        style = style or self.default_style
        w = style.page_width

        title = doc.get("title", "LEGAL DOCUMENT")
        court = doc.get("court", "")
        case_number = doc.get("case_number", "")
        plaintiff = doc.get("plaintiff", "[PLAINTIFF]")
        defendant = doc.get("defendant", "[DEFENDANT]")
        attorney = doc.get("attorney", "[ATTORNEY NAME]")
        bar_number = doc.get("bar_number", "[BAR NO.]")
        firm = doc.get("firm", "[LAW FIRM NAME]")
        sections = doc.get("sections", [])
        date_str = doc.get("date", _fmt.format_date())

        lines: List[str] = []

        # Header / Logo
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.logo_text, w))
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append("")

        # Court caption
        if court:
            lines.append(_fmt.center(court.upper(), w))
            lines.append(_fmt.horizontal_rule(w, "─"))
        if case_number:
            lines.append(_fmt.center(f"Case No.: {case_number}", w))
        lines.append("")

        # Parties
        lines.append(f"  {plaintiff.upper()},")
        lines.append("                                               Plaintiff,")
        lines.append("")
        lines.append("    v.")
        lines.append("")
        lines.append(f"  {defendant.upper()},")
        lines.append("                                               Defendant.")
        lines.append(_fmt.horizontal_rule(w, "─"))
        lines.append("")

        # Document title
        lines.append(_fmt.center(title.upper(), w))
        lines.append(_fmt.center(f"Dated: {date_str}", w))
        lines.append("")
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append("")

        # Introduction / Comes Now
        intro = doc.get("introduction", f"COMES NOW {plaintiff}, by and through undersigned counsel, and respectfully submits this {title} as follows:")
        lines.append(_fmt.wrap(intro, w - 4, "    "))
        lines.append("")

        # Numbered sections with Roman numerals
        if sections:
            for idx, sec in enumerate(sections, 1):
                sec_title = sec.get("title", f"SECTION {idx}")
                lines.append(_fmt.roman_section(idx, sec_title))
                lines.append("")
                # Sub-sections (A., B., C.)
                subsections = sec.get("subsections", [])
                if subsections:
                    for sidx, sub in enumerate(subsections):
                        sub_label = chr(ord("A") + sidx)
                        sub_title = sub.get("title", "")
                        lines.append(f"  {sub_label}. {sub_title}")
                        sub_body = sub.get("body", "")
                        if sub_body:
                            lines.append(_fmt.wrap(sub_body, w - 8, "      "))
                        # numbered items
                        items = sub.get("items", [])
                        if items:
                            lines.append(_fmt.numbered_list(items))
                        # lettered sub-items
                        alpha_items = sub.get("alpha_items", [])
                        if alpha_items:
                            lines.append(_fmt.alpha_list(alpha_items))
                        lines.append("")
                else:
                    body = sec.get("body", "")
                    if body:
                        lines.append(_fmt.wrap(body, w - 4, "    "))
                    items = sec.get("items", [])
                    if items:
                        lines.append(_fmt.numbered_list(items))
                    lines.append("")
        else:
            lines.append("    [DOCUMENT BODY — INSERT CONTENT HERE]")
            lines.append("")

        # Prayer for Relief / Conclusion
        conclusion = doc.get("conclusion", "WHEREFORE, the foregoing premises considered, undersigned counsel respectfully requests that this Court grant the relief requested herein.")
        lines.append(_fmt.horizontal_rule(w, "─"))
        lines.append("")
        lines.append("    " + _fmt.wrap(conclusion, w - 4, "    ").strip())
        lines.append("")

        # Signature block
        lines += self._signature_block_legal(
            attorney=attorney,
            bar_number=bar_number,
            firm=firm,
            date_str=date_str,
            doc=doc,
            width=w,
        )

        # Certificate of service
        lines += self._certificate_of_service(doc, w)

        # Footer
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.footer_text, w))
        lines.append(_fmt.horizontal_rule(w, "═"))

        content_text = "\n".join(lines)
        content_html = _fmt.text_to_html(content_text, title, style)
        content_markdown = _fmt.text_to_markdown(content_text, title)

        page_count = max(1, len(lines) // 55)
        return RenderedDocument(
            title=title,
            content_markdown=content_markdown,
            content_html=content_html,
            content_text=content_text,
            style=style,
            metadata={"court": court, "case_number": case_number, "date": date_str},
            page_count=page_count,
        )

    def render_financial_report(
        self,
        report: Dict[str, Any],
        style: Optional[DocumentStyle] = None,
    ) -> RenderedDocument:
        """Render a professional financial report."""
        style = style or self.default_style
        w = style.page_width

        title = report.get("title", "FINANCIAL REPORT")
        subtitle = report.get("subtitle", "")
        prepared_by = report.get("prepared_by", "[PREPARER NAME]")
        prepared_for = report.get("prepared_for", "[RECIPIENT]")
        date_str = report.get("date", _fmt.format_date())
        sections = report.get("sections", [])
        key_metrics = report.get("key_metrics", {})
        footnotes = report.get("footnotes", [])

        lines: List[str] = []

        # Header box
        header_lines = [
            _fmt.center(style.logo_text, w - 4),
            "",
            _fmt.center(title.upper(), w - 4),
        ]
        if subtitle:
            header_lines.append(_fmt.center(subtitle, w - 4))
        header_lines += [
            "",
            _fmt.center(f"As of: {date_str}", w - 4),
        ]
        lines.append(_fmt.box(header_lines, w))
        lines.append("")

        # Prepared by / for
        lines.append(f"  Prepared By:  {prepared_by}")
        lines.append(f"  Prepared For: {prepared_for}")
        lines.append(f"  Date:         {date_str}")
        lines.append(_fmt.horizontal_rule(w, "─"))
        lines.append("")

        # Key metrics executive summary
        if key_metrics:
            lines.append("  EXECUTIVE SUMMARY — KEY METRICS")
            lines.append("  " + "─" * (w - 4))
            col_w = (w - 6) // 2
            for k, v in key_metrics.items():
                label = str(k)[:col_w - 2].ljust(col_w - 2)
                val = str(v)
                lines.append(f"  │ {label}  {val}")
            lines.append("  " + "─" * (w - 4))
            lines.append("")

        # Report sections
        for idx, sec in enumerate(sections, 1):
            sec_title = sec.get("title", f"Section {idx}")
            lines.append(_fmt.section_header(str(idx), sec_title, w))
            body = sec.get("body", "")
            if body:
                lines.append(_fmt.wrap(body, w - 4, "  "))
                lines.append("")
            # Tables
            tables = sec.get("tables", [])
            for tbl in tables:
                lines.append(self._render_financial_table(tbl, w))
                lines.append("")

        # Footnotes
        if footnotes:
            lines.append(_fmt.horizontal_rule(w, "─"))
            lines.append("  FOOTNOTES AND DISCLAIMERS")
            for i, fn in enumerate(footnotes, 1):
                lines.append(f"  ({i}) {_fmt.wrap(fn, w - 6, '      ').strip()}")
            lines.append("")

        # Disclaimer
        lines.append(_fmt.horizontal_rule(w, "─"))
        disclaimer = report.get("disclaimer", "This report is prepared for informational purposes only. Past performance does not guarantee future results. This is not investment advice.")
        lines.append("  DISCLAIMER:")
        lines.append(_fmt.wrap(disclaimer, w - 4, "  "))
        lines.append("")

        # Footer
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.footer_text, w))
        lines.append(_fmt.horizontal_rule(w, "═"))

        content_text = "\n".join(lines)
        return RenderedDocument(
            title=title,
            content_markdown=_fmt.text_to_markdown(content_text, title),
            content_html=_fmt.text_to_html(content_text, title, style),
            content_text=content_text,
            style=style,
            metadata={"prepared_by": prepared_by, "date": date_str},
            page_count=max(1, len(lines) // 55),
        )

    def render_letter(
        self,
        letter: Dict[str, Any],
        style: Optional[DocumentStyle] = None,
    ) -> RenderedDocument:
        """Render a professional business letter in full block format."""
        style = style or self.default_style
        w = style.page_width

        sender_name = letter.get("sender_name", "[SENDER NAME]")
        sender_title = letter.get("sender_title", "")
        sender_firm = letter.get("sender_firm", "")
        sender_address = letter.get("sender_address", "[ADDRESS]")
        sender_city_state = letter.get("sender_city_state", "[CITY, STATE ZIP]")
        sender_phone = letter.get("sender_phone", "")
        sender_email = letter.get("sender_email", "")

        recipient_name = letter.get("recipient_name", "[RECIPIENT NAME]")
        recipient_title = letter.get("recipient_title", "")
        recipient_firm = letter.get("recipient_firm", "")
        recipient_address = letter.get("recipient_address", "[ADDRESS]")
        recipient_city_state = letter.get("recipient_city_state", "[CITY, STATE ZIP]")

        date_str = letter.get("date", _fmt.format_date())
        subject = letter.get("subject", "")
        salutation = letter.get("salutation", f"Dear {recipient_name}:")
        body_paragraphs = letter.get("body_paragraphs", ["[LETTER BODY]"])
        closing = letter.get("closing", "Very truly yours,")
        cc_list = letter.get("cc", [])
        enclosures = letter.get("enclosures", [])
        via = letter.get("via", "")

        lines: List[str] = []

        # Letterhead
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.logo_text, w))
        if sender_firm:
            lines.append(_fmt.center(sender_firm.upper(), w))
        lines.append(_fmt.center(sender_address, w))
        lines.append(_fmt.center(sender_city_state, w))
        if sender_phone:
            lines.append(_fmt.center(f"Tel: {sender_phone}", w))
        if sender_email:
            lines.append(_fmt.center(f"Email: {sender_email}", w))
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append("")

        # Date
        lines.append(date_str)
        lines.append("")

        # Via line
        if via:
            lines.append(via)
            lines.append("")

        # Recipient address
        lines.append(recipient_name)
        if recipient_title:
            lines.append(recipient_title)
        if recipient_firm:
            lines.append(recipient_firm)
        lines.append(recipient_address)
        lines.append(recipient_city_state)
        lines.append("")

        # Re: line
        if subject:
            lines.append(f"Re:    {subject}")
            lines.append(_fmt.horizontal_rule(min(60, w), "─"))
            lines.append("")

        # Salutation
        lines.append(salutation)
        lines.append("")

        # Body paragraphs
        for para in body_paragraphs:
            lines.append(_fmt.wrap(para, w - 2, "  "))
            lines.append("")

        # Closing
        lines.append(closing)
        lines.append("")
        lines.append("")
        lines.append("")
        lines.append(f"  {sender_name}")
        if sender_title:
            lines.append(f"  {sender_title}")
        if sender_firm:
            lines.append(f"  {sender_firm}")
        lines.append("")

        # CC
        if cc_list:
            lines.append("cc:    " + cc_list[0])
            for cc in cc_list[1:]:
                lines.append("       " + cc)
            lines.append("")

        # Enclosures
        if enclosures:
            lines.append(f"Encl:  ({len(enclosures)})")
            for enc in enclosures:
                lines.append(f"       {enc}")
            lines.append("")

        # Footer
        lines.append(_fmt.horizontal_rule(w, "─"))
        lines.append(_fmt.center(style.footer_text, w))

        title = f"Letter — {subject or recipient_name}"
        content_text = "\n".join(lines)
        return RenderedDocument(
            title=title,
            content_markdown=_fmt.text_to_markdown(content_text, title),
            content_html=_fmt.text_to_html(content_text, title, style),
            content_text=content_text,
            style=style,
            metadata={"date": date_str, "recipient": recipient_name},
            page_count=max(1, len(lines) // 55),
        )

    def render_contract(
        self,
        contract: Dict[str, Any],
        style: Optional[DocumentStyle] = None,
    ) -> RenderedDocument:
        """Render a professional contract with full formatting."""
        style = style or self.default_style
        w = style.page_width

        title = contract.get("title", "AGREEMENT")
        effective_date = contract.get("effective_date", "[DATE]")
        parties = contract.get("parties", [])
        recitals = contract.get("recitals", [])
        sections = contract.get("sections", [])
        exhibits = contract.get("exhibits", [])
        governing_law = contract.get("governing_law", "[STATE]")
        date_str = contract.get("date", _fmt.format_date())

        lines: List[str] = []

        # Header
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.logo_text, w))
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append("")
        lines.append(_fmt.center(title.upper(), w))
        lines.append("")
        lines.append(_fmt.center(f"Effective Date: {effective_date}", w))
        lines.append(_fmt.horizontal_rule(w, "─"))
        lines.append("")

        # Parties
        if parties:
            lines.append("PARTIES:")
            lines.append("")
            for p in parties:
                p_name = p.get("name", "[PARTY NAME]")
                p_type = p.get("type", "Party")
                p_addr = p.get("address", "")
                p_state = p.get("state", "")
                lines.append(f"  {p_type.upper()}: {p_name.upper()} (\"{''.join(w for w in p_type.split()).upper()}\")")
                if p_addr:
                    lines.append(f"    Address: {p_addr}")
                if p_state:
                    lines.append(f"    State of Formation: {p_state}")
                lines.append("")

        # Recitals (WHEREAS clauses)
        if recitals:
            lines.append(_fmt.horizontal_rule(w, "─"))
            lines.append("RECITALS")
            lines.append("")
            for i, rec in enumerate(recitals):
                lines.append(f"  WHEREAS, {_fmt.wrap(rec, w - 12, '           ').strip()};")
                lines.append("")
            lines.append("  NOW, THEREFORE, in consideration of the mutual promises, covenants, and")
            lines.append("  agreements set forth herein, and for other good and valuable consideration,")
            lines.append("  the receipt and sufficiency of which are hereby acknowledged, the parties")
            lines.append("  agree as follows:")
            lines.append("")

        # Sections
        if sections:
            for idx, sec in enumerate(sections, 1):
                sec_title = sec.get("title", f"SECTION {idx}")
                lines.append(f"SECTION {idx}. {sec_title.upper()}")
                lines.append("")
                subsections = sec.get("subsections", [])
                if subsections:
                    for sidx, sub in enumerate(subsections, 1):
                        sub_title = sub.get("title", "")
                        sub_body = sub.get("body", "")
                        lines.append(f"  {idx}.{sidx} {sub_title}")
                        if sub_body:
                            lines.append(_fmt.wrap(sub_body, w - 6, "      "))
                        lines.append("")
                else:
                    body = sec.get("body", "")
                    if body:
                        lines.append(_fmt.wrap(body, w - 4, "    "))
                    lines.append("")
        else:
            lines.append("SECTION 1. TERMS AND CONDITIONS")
            lines.append("")
            lines.append("    [INSERT AGREEMENT TERMS HERE]")
            lines.append("")

        # Governing Law
        lines.append(f"GOVERNING LAW. This Agreement shall be governed by the laws of the State")
        lines.append(f"of {governing_law}, without regard to its conflict of law provisions.")
        lines.append("")

        # Exhibits
        if exhibits:
            lines.append(_fmt.horizontal_rule(w, "─"))
            lines.append("EXHIBITS:")
            for ex in exhibits:
                lines.append(f"  Exhibit {ex.get('label', 'A')} — {ex.get('title', '[EXHIBIT TITLE]')}")
            lines.append("")

        # Signature page
        lines += self._signature_page_contract(parties, date_str, w)

        # Footer
        lines.append(_fmt.horizontal_rule(w, "═"))
        lines.append(_fmt.center(style.footer_text, w))
        lines.append(_fmt.horizontal_rule(w, "═"))

        content_text = "\n".join(lines)
        return RenderedDocument(
            title=title,
            content_markdown=_fmt.text_to_markdown(content_text, title),
            content_html=_fmt.text_to_html(content_text, title, style),
            content_text=content_text,
            style=style,
            metadata={"effective_date": effective_date, "governing_law": governing_law},
            page_count=max(1, len(lines) // 55),
        )

    def create_document_package(
        self,
        documents: List[Dict[str, Any]],
        cover_page: Dict[str, Any],
        style: Optional[DocumentStyle] = None,
    ) -> DocumentPackage:
        """Create a multi-document package with cover page and TOC."""
        style = style or self.default_style
        w = style.page_width

        pkg_title = cover_page.get("title", "DOCUMENT PACKAGE")
        pkg_subtitle = cover_page.get("subtitle", "")
        pkg_date = cover_page.get("date", _fmt.format_date())
        pkg_prepared_by = cover_page.get("prepared_by", style.logo_text)
        confidentiality = cover_page.get(
            "confidentiality",
            "CONFIDENTIAL — This document package contains privileged and confidential information. "
            "Unauthorized use, disclosure, or distribution is strictly prohibited.",
        )

        # Build cover page
        cover_lines = [
            _fmt.horizontal_rule(w, "═"),
            _fmt.center(style.logo_text, w),
            _fmt.horizontal_rule(w, "═"),
            "",
            "",
            _fmt.center("━" * 40, w),
            _fmt.center(pkg_title.upper(), w),
            "",
        ]
        if pkg_subtitle:
            cover_lines.append(_fmt.center(pkg_subtitle, w))
        cover_lines += [
            _fmt.center("━" * 40, w),
            "",
            "",
            _fmt.center(f"Prepared: {pkg_date}", w),
            _fmt.center(f"By: {pkg_prepared_by}", w),
            "",
            "",
            _fmt.horizontal_rule(w, "─"),
            _fmt.wrap(confidentiality, w - 4, "  "),
            _fmt.horizontal_rule(w, "─"),
        ]
        cover_text = "\n".join(cover_lines)

        # Render each document
        rendered: List[RenderedDocument] = []
        doc_renderer_map = {
            "legal": self.render_legal_document,
            "financial": self.render_financial_report,
            "letter": self.render_letter,
            "contract": self.render_contract,
        }

        for doc in documents:
            doc_type = doc.get("type", "legal")
            renderer = doc_renderer_map.get(doc_type, self.render_legal_document)
            rendered.append(renderer(doc, style))

        # Build TOC
        toc_lines = [
            _fmt.horizontal_rule(w, "═"),
            _fmt.center("TABLE OF CONTENTS", w),
            _fmt.horizontal_rule(w, "═"),
            "",
        ]
        page = 2
        for i, doc in enumerate(rendered, 1):
            tab_label = f"Tab {i}: {doc.title}"
            page_ref = f"Page {page}"
            toc_lines.append(f"  {tab_label:<{w - 20}}  {page_ref:>10}")
            page += doc.page_count
        toc_lines.append("")
        toc_text = "\n".join(toc_lines)

        return DocumentPackage(
            cover_page=cover_text,
            table_of_contents=toc_text,
            sections=rendered,
            unified_style=style,
        )

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _signature_block_legal(
        self,
        attorney: str,
        bar_number: str,
        firm: str,
        date_str: str,
        doc: Dict[str, Any],
        width: int,
    ) -> List[str]:
        lines = [
            "    " + " " * 40 + "Respectfully submitted,",
            "",
            "    " + " " * 40 + firm,
            "",
            "    " + " " * 40 + "/s/ " + attorney,
            "    " + " " * 40 + attorney,
            "    " + " " * 40 + f"Bar No. {bar_number}",
            "    " + " " * 40 + firm,
        ]
        address = doc.get("firm_address", "[FIRM ADDRESS]")
        city = doc.get("firm_city_state", "[CITY, STATE ZIP]")
        phone = doc.get("firm_phone", "[PHONE]")
        email = doc.get("firm_email", "[EMAIL]")
        lines += [
            "    " + " " * 40 + address,
            "    " + " " * 40 + city,
            "    " + " " * 40 + f"Tel: {phone}",
            "    " + " " * 40 + f"Email: {email}",
            "",
            "    " + f"Dated: {date_str}",
            "",
        ]
        return lines

    def _certificate_of_service(self, doc: Dict[str, Any], width: int) -> List[str]:
        date_str = doc.get("date", _fmt.format_date())
        served_parties = doc.get("served_parties", ["[OPPOSING COUNSEL]"])
        lines = [
            _fmt.horizontal_rule(width, "─"),
            "",
            _fmt.center("CERTIFICATE OF SERVICE", width),
            "",
            "    I hereby certify that on this date, I caused a true and correct copy of",
            "    the foregoing document to be served upon the following parties via the",
            "    Court's electronic filing system (ECF) and/or U.S. Mail:",
            "",
        ]
        for party in served_parties:
            lines.append(f"        • {party}")
        lines += [
            "",
            f"    Dated: {date_str}",
            "",
            "                                        /s/ [ATTORNEY NAME]",
            "                                        [ATTORNEY NAME]",
            "",
        ]
        return lines

    def _signature_page_contract(
        self,
        parties: List[Dict[str, Any]],
        date_str: str,
        width: int,
    ) -> List[str]:
        lines = [
            "─" * width,
            _fmt.center("SIGNATURE PAGE", width),
            "─" * width,
            "",
            "  IN WITNESS WHEREOF, the parties have executed this Agreement as of the",
            f"  date first written above.",
            "",
        ]
        col_w = (width - 10) // 2
        if not parties:
            parties = [
                {"name": "[PARTY A]", "type": "First Party"},
                {"name": "[PARTY B]", "type": "Second Party"},
            ]
        for i, party in enumerate(parties):
            p_name = party.get("name", "[PARTY NAME]")
            p_type = party.get("type", "Party")
            lines += [
                f"  {p_type.upper()}:",
                "",
                f"  {p_name.upper()}",
                "",
                "  By: ___________________________________",
                "      Name:  ____________________________",
                "      Title: ____________________________",
                "      Date:  ____________________________",
                "",
                "  NOTARIZATION (if applicable):",
                "  State of ________________",
                "  County of _______________",
                "",
                "  Subscribed and sworn to before me this ___ day of ___________, 20___.",
                "",
                "  _____________________________",
                "  Notary Public",
                "  My Commission Expires: _______",
                "",
                "─" * (width // 2),
                "",
            ]
        lines.append(f"  Governing Law: This Agreement is governed by applicable law.")
        lines.append("")
        return lines

    def _render_financial_table(self, tbl: Dict[str, Any], width: int) -> str:
        headers = tbl.get("headers", ["Description", "Amount"])
        rows = tbl.get("rows", [])
        totals = tbl.get("totals", {})

        n_cols = len(headers)
        col_w = (width - 4) // n_cols

        def row_str(cells: List[str]) -> str:
            parts = []
            for c in cells:
                parts.append(str(c)[:col_w - 2].ljust(col_w - 2))
            return "  │ " + " │ ".join(parts) + " │"

        lines = []
        sep = "  ├" + "┼".join(["─" * col_w] * n_cols) + "┤"
        top = "  ┌" + "┬".join(["─" * col_w] * n_cols) + "┐"
        bot = "  └" + "┴".join(["─" * col_w] * n_cols) + "┘"

        lines.append(top)
        lines.append(row_str(headers))
        lines.append(sep)

        for row in rows:
            if isinstance(row, dict):
                cells = [row.get(h, "") for h in headers]
            elif isinstance(row, (list, tuple)):
                cells = list(row)
            else:
                cells = [str(row)]
            # Pad or truncate to n_cols
            while len(cells) < n_cols:
                cells.append("")
            lines.append(row_str(cells[:n_cols]))

        if totals:
            lines.append(sep)
            tot_cells = [totals.get(h, "") for h in headers]
            lines.append(row_str(tot_cells[:n_cols]))

        lines.append(bot)
        return "\n".join(lines)
